DIA 01 - Importando dados

In [1]:
#IMPORTANDO BIBLIOTECAS
import pandas as pd
import plotly_express as px
import os

#IMPORTANDO DATASETS
caminho_datasets = 'datasets'
lista_de_diretorios = os.listdir(caminho_datasets)

dfs = []

for arquivo in lista_de_diretorios:
    if arquivo.endswith('.csv'):
        caminho_completo = os.path.join(caminho_datasets, arquivo)
        df = pd.read_csv(caminho_completo)
        dfs.append(df)
    
df_emprestimos_biblioteca = pd.concat(dfs, ignore_index= True)

In [2]:
df_emprestimos_biblioteca

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

In [3]:
df_emprestimos_biblioteca.value_counts()

id_emprestimo  codigo_barras  data_renovacao                 data_emprestimo                data_devolucao                 matricula_ou_siape  tipo_vinculo_usuario
709705         2009032168     2010/01/17 18:56:43.909000000  2010/01/04 09:58:46.549000000  2010/01/20 13:14:34.464000000  2.008010e+09        ALUNO DE GRADUAÇÃO        7
709704         2006021442     2010/01/17 18:56:43.923000000  2010/01/04 09:58:46.522000000  2010/02/01 13:59:02.528000000  2.008010e+09        ALUNO DE GRADUAÇÃO        7
709698         2009047725     2010/01/18 14:44:41.163000000  2010/01/04 09:21:19.099000000  2010/02/02 12:02:38.444000000  2.009047e+09        ALUNO DE GRADUAÇÃO        3
709686         2006017618     2010/01/26 08:07:01.738000000  2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000  2.008112e+09        ALUNO DE PÓS-GRADUAÇÃO    2
709687         L184117        2010/01/18 11:07:46.470000000  2010/01/04 08:24:21.284000000  2010/02/03 08:58:45.692000000  2.007211e+08        ALUNO DE GRADUAÇÃO        2
                                                                                                                                                                        ..
10322140       2012043425     2018/01/29 21:31:14.254000000  2017/12/29 14:11:46.562000000  2018/02/27 14:49:44.000000000  2.016201e+09        ALUNO DE PÓS-GRADUAÇÃO    1
10322144       2012052321     2018/01/29 21:31:14.235000000  2017/12/29 14:11:46.621000000  2018/02/27 14:49:18.000000000  2.016201e+09        ALUNO DE PÓS-GRADUAÇÃO    1
10322148       2013114500     2018/01/29 21:31:14.215000000  2017/12/29 14:11:46.680000000  2018/02/27 14:49:53.000000000  2.016201e+09        ALUNO DE PÓS-GRADUAÇÃO    1
10322152       2014057666     2018/01/29 21:31:14.192000000  2017/12/29 14:11:46.742000000  2018/02/27 14:49:33.000000000  2.016201e+09        ALUNO DE PÓS-GRADUAÇÃO    1
10322156       2014057679     2018/01/29 21:31:14.169000000  2017/12/29 14:11:46.806000000  2018/02/27 14:49:07.000000000  2.016201e+09        ALUNO DE PÓS-GRADUAÇÃO    1
Name: count, Length: 968028, dtype: int64

In [4]:
df_emprestimos_biblioteca = df_emprestimos_biblioteca.drop_duplicates()
df_emprestimos_biblioteca

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

Importando banco de dados .parquet

In [5]:
dados_exemplares = pd.read_parquet('datasets/dados_exemplares.parquet')
dados_exemplares

,id_exemplar,codigo_barras,colecao,biblioteca,status_material,localizacao,registro_sistema
index,,,,,,,
0,5,L000003,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,694,1
1,4,L000002,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,688,1
2,3,L000001,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,638,1
3,7,L000114,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,616,5
5,10,L000041,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,657,15
...,...,...,...,...,...,...,...
568580,1353472,2021011150,Acervo Circulante,Biblioteca Setorial do Núcleo de Educação da I...,REGULAR,951,268231
568581,1353473,2019013454,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,997,268233
568582,1353474,2019012811,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,987,268234
568583,1353475,2019013451,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,764,268235
568584,1353476,2019012276,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,962,268236

Unindo os dois datasets

In [6]:
df_emprestimos_completo = pd.merge(df_emprestimos_biblioteca, dados_exemplares, on= 'codigo_barras')
df_emprestimos_completo

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,25009
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,75019
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,44494
4,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,91736
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,110098
2072518,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,110171
2072519,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,134173
2072520,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,67712
2072521,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,205153

In [7]:
df_emprestimos_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    float64
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
 12  registro_sistema      int64
dtypes: float64(1), int64(4), object(8)
memory usage: 205.6+ MB

DIA 02 - Primeiras manipulações

Criação da coluna 'Classificação CDU' baseada na coluna localização.

In [8]:
df_emprestimos_completo['classe_CDU'] = pd.cut(df_emprestimos_completo['localizacao'], bins= [0, 99, 199, 299,399,499,599,699,799,899,999], labels= ['Generalidades. Ciência e conhecimento', 'Filosofia e psicologia', 'Religião', 'Ciências Sociais', 'Classe vaga', 'Matemática e ciências naturais', 'Ciências aplicadas', 'Belas artes', 'Linguagem. Língua. Linguística', 'Geografia. Biografia. História'] )
df_emprestimos_completo

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema,classe_CDU
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225,Ciências aplicadas
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,25009,Ciências aplicadas
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,75019,Ciências aplicadas
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,44494,Ciências aplicadas
4,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,91736,Ciências aplicadas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,110098,Ciências aplicadas
2072518,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,110171,Ciências aplicadas
2072519,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,134173,Ciências aplicadas
2072520,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,67712,Ciências aplicadas
2072521,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,205153,Generalidades. Ciência e conhecimento

Excluindo a coluna 'registro_sistema'

In [9]:
df_emprestimos_completo.drop(columns='registro_sistema', inplace=True)
df_emprestimos_completo

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,classe_CDU
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,Ciências aplicadas
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,Ciências aplicadas
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,Ciências aplicadas
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,Ciências aplicadas
4,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,Ciências aplicadas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,Ciências aplicadas
2072518,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,Ciências aplicadas
2072519,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,Ciências aplicadas
2072520,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,Ciências aplicadas
2072521,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,Generalidades. Ciência e conhecimento

Verificando o tipo da coluna 'matricula_ou_siape' e convertendo-a para string

In [10]:
df_emprestimos_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    float64
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
 12  classe_CDU            category
dtypes: category(1), float64(1), int64(3), object(8)
memory usage: 191.7+ MB

In [11]:
df_emprestimos_completo['matricula_ou_siape'] = df_emprestimos_completo['matricula_ou_siape'].astype('string')
df_emprestimos_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    string
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
 12  classe_CDU            category
dtypes: category(1), int64(3), object(8), string(1)
memory usage: 191.7+ MB

DIA 03 - Explorando DATETIME dos dados

Verificando a relação entre empréstimo e empréstimo de exemplares

Salvando dataframe df_emprestimos_completo

In [93]:
pasta = 'resultados'

if not os.path.exists(pasta):
    os.makedirs(pasta)

caminho_pasta_completo = os.path.join(pasta, 'df_emprestimos_completo.parquet')

df_emprestimos_completo.to_parquet(caminho_pasta_completo, index= False)

print(f'Salvo em^: {caminho_pasta_completo}')

Salvo em^: resultados\df_emprestimos_completo.parquet

In [12]:
df_emprestimos_completo['id_emprestimo'].value_counts()

id_emprestimo
2010326    3
1752337    3
2014596    3
2422542    3
1987946    3
          ..
709699     1
709700     1
709702     1
709703     1
2989090    1
Name: count, Length: 2068724, dtype: int64

In [13]:
df_emprestimos_completo.loc[df_emprestimos_completo['id_emprestimo'] == 2772079].reset_index()

,index,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,classe_CDU
0,1864848,2772079,2010082016,2018/12/03 16:05:57.708000000,2018/11/22 18:28:01.619000000,2018/12/11 17:54:14.000000000,20182022833.0,ALUNO DE PÓS-GRADUAÇÃO,1055570,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,670,Ciências aplicadas
1,1864849,2772079,2010082016,2018/12/03 16:05:57.708000000,2018/11/22 18:28:01.619000000,2018/12/11 17:54:14.000000000,20182022833.0,ALUNO DE PÓS-GRADUAÇÃO,1055922,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,693,Ciências aplicadas
2,1864850,2772079,2010082016,2018/12/03 16:05:57.708000000,2018/11/22 18:28:01.619000000,2018/12/11 17:54:14.000000000,20182022833.0,ALUNO DE PÓS-GRADUAÇÃO,1056360,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,389,Ciências Sociais

Essa análise mostra que "id_emprestimo" é cada empréstimo realizado que pode ter 1 ou mais exemplares.
Assim cada linha é o empréstimo de cada exemplar.

Valor total de empréstimos

In [14]:
emprestimos = len(df_emprestimos_completo['id_emprestimo'].unique())
emprestimos

2068724

Exemplares totais emprestados

In [15]:
exemplares = len(df_emprestimos_completo['id_emprestimo'])
exemplares

2072522

In [16]:
df_emprestimos_biblioteca

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

Quantidade de exemplares emprestados por ano

Primeiro converter  coluna de data para uma data válida

In [17]:
df_emprestimos_completo['data_emprestimo'] = pd.to_datetime(df_emprestimos_completo['data_emprestimo'])

In [18]:
emprestimo_ano = df_emprestimos_completo.groupby(df_emprestimos_completo['data_emprestimo'].dt.year)['id_emprestimo'].size()
emprestimo_ano.index.name ='ano'
emprestimo_ano.name = 'quantidade'
emprestimo_ano = emprestimo_ano.reset_index()

Salvando empréstimos por ano?

Impressão gráfico de linha:

In [19]:
fig = px.line(
    emprestimo_ano,
    x = 'ano',
    y = 'quantidade',
    labels= {
        'ano': 'Ano',
        'quantidade':'Empréstimos'
        },
    title = 'Quantidade de exemplares emprestados do SISBI ao longo dos anos',
    subtitle= '2010 a 2020',
    width = 1000,
    height = 500
)

In [20]:
def ajusta_layout_grafico(fig):
    
    fig.update_layout(
        title_font = dict(size=20, family='Arial', color='black'),
    )

    fig.update_xaxes(
        title_font = dict(size=15, family='Arial'),
        tickfont = dict(size=15, family='Arial'),
        side = 'bottom' # 'bottom' é o padrão, mas é bom para garantir
    )

    fig.update_yaxes(
        title_font = dict(size=15, family='Arial'),
        tickfont = dict(size=15, family='Arial')
    )

In [21]:
fig.show()
ajusta_layout_grafico(fig)

1 - O número de empréstimos começou a diminuir em 2013, tendo queda vertiginosa em 2019.

2 - O ano de 2020 não pode ser valiado igual, pois possui poucos dados.

É importante a direção da biblioteca investigar o que está ocorrendo desde 2013 com os procedimentos realizados. Alguns questionamentos importantes que deve-se levar a direção, para que seja aprofundada em outra análise:

O número de alunos da universidade vem diminuindo?
Como está a pesquisa de satisfação dos usuários da biblioteca?
O acervo está atualizado?
Quais são as estratégias de marketing que a biblioteca está realizando?
O que ocorreu de diferente em 2017 em relação a 2016 e 2015 para que o número tenha se elevado?
E em 2019?

Anlisando a quantidade de empréstimos por mês.

In [22]:
emprestimos_mes = df_emprestimos_completo.groupby(df_emprestimos_completo['data_emprestimo'].dt.month)['id_emprestimo'].size()
emprestimos_mes.index.name = 'mes'
emprestimos_mes.name = 'quantidade'
emprestimos_mes = emprestimos_mes.reset_index()
emprestimos_mes

    mes  quantidade
0     1       67514
1     2      210200
2     3      252185
3     4      208725
4     5      202530
5     6      138123
6     7      123790
7     8      232793
8     9      208234
9    10      188410
10   11      164222
11   12       75796

In [23]:
emprestimos_mes['mes'] = emprestimos_mes['mes'].replace({
    1: 'Janeiro', 2: 'Fevereiro', 3:'Março',
    4: 'Abril', 5: 'Maio', 6: 'Junho',
    7: 'Julho', 8:'Agosto', 9:'Setembro',
    10: 'Outubro', 11: 'Novembro', 12:'Dezembro'

})

In [24]:
emprestimos_mes

          mes  quantidade
0     Janeiro       67514
1   Fevereiro      210200
2       Março      252185
3       Abril      208725
4        Maio      202530
5       Junho      138123
6       Julho      123790
7      Agosto      232793
8    Setembro      208234
9     Outubro      188410
10   Novembro      164222
11   Dezembro       75796

Plotando o gráfico.

In [25]:
fig = px.line(
    emprestimos_mes,
    x = 'mes',
    y = 'quantidade',
    labels = dict(
        mes = 'Mêses',
        quantidade = 'Empréstimos'
    ),
    title = 'Quantidade de exemplares emprestados do SISBI ao longo do ano',
    width= 1200,
    height= 500
)

In [26]:
fig.show()
ajusta_layout_grafico(fig)

1 - Pode-se observar que os meses com maiores números de exemplares emprestados é Março e Agosto

2 - Por ser uma biblioteca universitária faz sentido o comportamento de vale nos meses de Janeiro, Julho e Dezembro, devido ao período de férias.

3 - Não é novidade, mas vale ficar atento que mesmo com a baixa de empréstimos, se todos os colaboradores saíorem de férias a bibliotéca pode não funcionar.
Ainda mais com períodos de inventário que ocorrem uma vez ao ano, ou de dois em dois anos, e o melhor período seria de Dezembro a Janeiro.
Dessa forma mesesd como Maio, Junho e Novembro poderiam ser considerados para isso.

4 - Ocorre uma queda grande no período de Junho. Cabe um alerta para inestigar o que pode estra ocorrendo e criar estratégias e ações de marketing para aumentar o número de exemplares emprestados. Um exemplo é: Uma acão de marketing para que sejam realizados empréstimos para leitura no período de férias.

Vamos analisar ao longo do dia.

In [27]:
emprestimos_hora = df_emprestimos_completo.groupby(df_emprestimos_completo['data_emprestimo'].dt.hour)['id_emprestimo'].size()
emprestimos_hora.index.name = 'hora'
emprestimos_hora.name = 'quantidade'
emprestimos_hora = emprestimos_hora.reset_index()
emprestimos_hora

    hora  quantidade
0      0          17
1      6          14
2      7       18777
3      8      103416
4      9      131273
5     10      185839
6     11      180048
7     12      148754
8     13      126987
9     14      150876
10    15      166672
11    16      210655
12    17      185340
13    18      182520
14    19      102129
15    20      127716
16    21       51191
17    22         247
18    23          51

Organizando valores e plotando gráfico

In [28]:
emprestimos_hora = emprestimos_hora.sort_values(ascending=True, by='quantidade')

In [29]:
fig = px.bar(
    emprestimos_hora,
    x = 'hora',
    y = 'quantidade',
    color='quantidade',
    color_continuous_scale= 'reds',
    labels={
        'hora': 'Horário (24h)',
        'quantidade': 'Quantidade de empréstimos'
    },
    title= 'Quantidade de empréstimos do SISBI ao longo do dia',
    width= 1300,
    height= 500
)

In [30]:
fig.show()
ajusta_layout_grafico(fig)

Através do gráfico é possível identificar que os períodos das 10 h e 16 h são os de maior pico no atendimento de empréstimos.

Períodos do começo da manhã (entre 7h e 9) e da noite (entre 19h e 22) podem ser os melhores horários para que se realizem as demais atividades além do atendimento.

DIA 04

Hoje você vai continuar a questionar ainda mais os seus dados para extrair ainda mais informações deles.

O objetivo será entender a quantidade de empréstimos a partir das variáveis categóricas do seu conjunto de dados.

Variável categórica? Mas o que é isso, Francisco?

Bom, um conjunto de dados é descrito pelas suas características que variam de acordo com cada um, por exemplo: peso, idade, quantidade de páginas, notas, nome da biblioteca, número de empréstimos, número de filhos, etc.

Elas podem ser classificadas em dois grandes grupos que se subdividem em mais dois outros grupos cada.

Quantitativas: são características numéricas que podemos enumerar:


Discreta: possuem apenas valores finitos enumeráveis. Exemplo: número de empréstimos, número de filhos, número de páginas.

Contínua: possuem valores dentro de um intervalo de números. Exemplo: altura, peso, notas.

Categóricas (ou qualitativas): são características não-numéricas para as quais podemos definir categorias.


Nominal: possuem categorias não ordenadas naturalmente. Exemplo: nomes, cores, tema do livro.

Ordinal: são categorias onde está implícito um tipo de ordenamento ou hierarquia. Exemplo: classe social, nível de escolaridade.

Vamos explorar algumas das variáveis categóricas das quais precisaremos extrair mais informações. Elas são:


Tipo de vínculo
Coleção
Biblioteca
Classificação geral da CDU

Ao se analisar uma nova variável, é bem interessante verificar cada uma listando quais são os valores únicos dentro delas.

Para explorar os dados, alguns questionamentos serão pertinentes para a diretoria das bibliotecas, como:


“Como se distribuem os empréstimos de exemplares pelos tipos de vínculo dos usuários?”
Desta forma, a diretoria poderá entender qual é o público que está utilizando a biblioteca e assim tomar decisões em continuar com a estratégia de negócio atual ou modificá-la.

Quais coleções são mais emprestadas?
Da mesma forma, as coleções. Ranquear as coleções mais emprestadas pelo público, será bastante importante para a estratégia atual.

Quais são as bibliotecas com mais ou menos quantidade de empréstimos?
Assim, a diretoria conseguirá entender onde ela deverá melhorar e focar suas iniciativas.

Você visualizará os dados dos empréstimos que aconteceram, mas e os dados que não estão aqui na análise?

Por quais outras perspectivas você pode entender essa tabela de como ela se formou? Comparar bibliotecas de tamanhos diferentes, com públicos diferentes, acervos diferentes... isso faz sentido para a diretoria do sistema de bibliotecas?

Aponte algumas outras métricas que poderiam entrar aqui para enriquecer essa análise.


De quais temas da CDU são os exemplares emprestados?

Entender quais os temas mais procurados pelos usuários é fundamental para o desenvolvimento de novos planos de marketing do acervo. Para que possam não apenas fortalecer o que está sendo utilizado, mas também promover o que não está.

Gere uma tabela de frequência e com o percentual para cada variável.

Como é um trabalho repetitivo, crie uma função que gere a tabela com os valores.

Após geradas as tabelas, traga algumas das suas percepções para as análises com o que você poderá contribuir para a diretoria da biblioteca.

Vamos explorar algumas das variáveis categóricas das quais precisaremos extrair mais informações. Elas são:

Tipo de vínculo Coleção Biblioteca Classificação geral da CDU

Ao se analisar uma nova variável, é bem interessante verificar cada uma listando quais são os valores únicos dentro delas.

In [31]:
df_emprestimos_completo['data_devolucao'] = pd.to_datetime(df_emprestimos_completo['data_devolucao'])
df_emprestimos_completo['data_renovacao'] = pd.to_datetime(df_emprestimos_completo['data_renovacao'])
df_emprestimos_completo

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,classe_CDU
0,709684,L095049,NaT,2010-01-04 07:44:10.721,2010-01-05 16:26:12.662,2008023265.0,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,Ciências aplicadas
1,709685,L167050,NaT,2010-01-04 07:44:10.750,2010-01-12 07:34:13.934,2008023265.0,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,Ciências aplicadas
2,709686,2006017618,2010-01-26 08:07:01.738,2010-01-04 08:08:44.081,2010-02-25 07:36:25.800,2008112114.0,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,Ciências aplicadas
3,709687,L184117,2010-01-18 11:07:46.470,2010-01-04 08:24:21.284,2010-02-03 08:58:45.692,200721119.0,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,Ciências aplicadas
4,709688,2007027500,2010-01-19 15:59:26.464,2010-01-04 08:27:33.569,2010-02-03 13:06:30.662,2009045971.0,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,Ciências aplicadas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989086,2008047044,NaT,2020-05-05 19:51:06.059,2021-05-13 14:53:31.000,3067431.0,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,Ciências aplicadas
2072518,2989087,2008047047,NaT,2020-05-05 19:51:06.135,2021-05-13 14:53:38.000,3067431.0,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,Ciências aplicadas
2072519,2989088,2010052905,NaT,2020-05-05 19:51:06.164,2021-05-13 15:01:46.000,3067431.0,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,Ciências aplicadas
2072520,2989089,2010048023,NaT,2020-06-09 11:54:02.669,2021-07-21 15:33:55.000,20201014993.0,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,Ciências aplicadas
2072521,2989090,2013106838,NaT,2020-06-09 11:54:02.852,2021-07-21 15:33:45.000,20201014993.0,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,Generalidades. Ciência e conhecimento

Verificando valores únicos

In [32]:
df_emprestimos_completo['tipo_vinculo_usuario'].unique()

array(['ALUNO DE GRADUAÇÃO', 'ALUNO DE PÓS-GRADUAÇÃO', 'DOCENTE',
       'SERVIDOR TÉCNICO-ADMINISTRATIVO', 'DOCENTE EXTERNO',
       'ALUNO MÉDIO/TÉCNICO', 'USUÁRIO EXTERNO', 'OUTROS'], dtype=object)

In [33]:
df_emprestimos_completo['colecao'].unique()

array(['Acervo Circulante', 'Folhetos', 'Teses', 'Dissertações',
       'Monografias', 'Publicações de Autores do RN',
       'Publicações da UFRN', 'Multimeios', 'Coleção Mossoroense',
       'Eventos', 'Trabalho Acadêmico', 'Obras de Referência',
       'Obras Raras', 'Literatura de Cordel', 'Coleção Zila Mamede',
       'Necessidades Educacionais Específicas'], dtype=object)

In [34]:
df_emprestimos_completo['biblioteca'].unique()

array(['Biblioteca Central Zila Mamede',
       'Biblioteca Setorial Prof. Rodolfo Helinski - Escola Agrícola de Jundiaí - EAJ  - Macaiba',
       'Biblioteca Setorial Bertha Cruz Enders - \xadEscola de Saúde da UFRN - ESUFRN',
       'Biblioteca Setorial do Centro Ciências da Saúde - CCS',
       'Biblioteca Setorial Prof. Alberto Moreira Campos - \xadDepartamento de Odontologia',
       'Biblioteca Setorial Prof. Ronaldo Xavier de Arruda - CCET',
       'Biblioteca Setorial do Centro de Ciências Humanas, Letras e Artes - CCHLA',
       'Biblioteca Setorial Prof. Horácio Nicolas Solimo - \xad Engenharia Química - EQ - CT',
       'Biblioteca Setorial Prof. Francisco Gurgel De Azevedo - Instituto Química - IQ',
       'Biblioteca Setorial do Centro Ciências Sociais Aplicadas - CCSA',
       'Biblioteca Setorial do Departamento de Artes - DEART',
       'Biblioteca Setorial Prof. Dr. Marcelo Bezerra de Melo Tinôco - DARQ - \xadCT',
       'Biblioteca Setorial Árvore do Conhecimento - Instituto do Cérebro - ICe',
       'Biblioteca Setorial Moacyr de Góes - CE',
       'Biblioteca Setorial Prof. Leopoldo Nelson - \xadCentro de Biociências - CB',
       'Biblioteca Setorial Dr. Paulo Bezerra - EMCM/RN - Caicó',
       'Biblioteca Setorial Pe. Jaime Diniz - Escola de Música - EMUFRN',
       'Biblioteca Setorial Profª. Maria Lúcia da Costa Bezerra - \xadCERES\xad - Caicó',
       'Biblioteca Setorial Profª. Maria José Mamede Galvão - FELCS - Currais Novos',
       'Biblioteca Setorial do Núcleo de Educação da Infância - NEI',
       'Biblioteca Setorial da Faculdade de Ciências da Saúde do Trairi - FACISA - Santa Cruz',
       'Biblioteca Setorial do Núcleo de Ensino Superior do Agreste - NESA - Nova Cruz'],
      dtype=object)

In [35]:
df_emprestimos_completo['classe_CDU'].unique()

['Ciências aplicadas', 'Linguagem. Língua. Linguística', 'Ciências Sociais', 'Geografia. Biografia. História', 'Matemática e ciências naturais', 'Religião', 'Generalidades. Ciência e conhecimento', 'Filosofia e psicologia', 'Belas artes', NaN]
Categories (10, object): ['Generalidades. Ciência e conhecimento' < 'Filosofia e psicologia' < 'Religião' < 'Ciências Sociais' ... 'Ciências aplicadas' < 'Belas artes' < 'Linguagem. Língua. Linguística' < 'Geografia. Biografia. História']

Função  que gera tabelas com frequência

In [36]:
def gera_tabela_frequencia(variavel):
    '''
    Esta função irá gerar uma tabela de frequência com percentuais de acordo
    com a variável passada.

    variavel = variável categórica escolhida de dentro do conjunto de dados
    emprestimos_completo
    '''
    dataframe = df_emprestimos_completo[variavel].value_counts()
    dataframe = dataframe.reset_index()
    dataframe.columns = [variavel, 'quantidade']
    dataframe['percentual'] = round((dataframe['quantidade']/dataframe['quantidade'].sum())*100, 1)

    return dataframe

In [37]:
gera_tabela_frequencia('tipo_vinculo_usuario')

              tipo_vinculo_usuario  quantidade  percentual
0               ALUNO DE GRADUAÇÃO     1612324        77.8
1           ALUNO DE PÓS-GRADUAÇÃO      302541        14.6
2                          DOCENTE       70981         3.4
3  SERVIDOR TÉCNICO-ADMINISTRATIVO       32184         1.6
4              ALUNO MÉDIO/TÉCNICO       28029         1.4
5                  DOCENTE EXTERNO       23949         1.2
6                  USUÁRIO EXTERNO        2509         0.1
7                           OUTROS           5         0.0

In [38]:
gera_tabela_frequencia('colecao')

                                  colecao  quantidade  percentual
0                       Acervo Circulante     2053120        99.1
1                              Multimeios        7954         0.4
2                             Monografias        4021         0.2
3                            Dissertações        2406         0.1
4                     Obras de Referência        1954         0.1
5            Publicações de Autores do RN         866         0.0
6                     Publicações da UFRN         764         0.0
7                                   Teses         714         0.0
8                                Folhetos         271         0.0
9   Necessidades Educacionais Específicas         130         0.0
10                     Trabalho Acadêmico         115         0.0
11                                Eventos         101         0.0
12                    Coleção Mossoroense          44         0.0
13                    Coleção Zila Mamede          30         0.0
14                   Literatura de Cordel          24         0.0
15                            Obras Raras           8         0.0

O acervo circulante corresponde a 99% do empréstimos, o que é um ponto de atenção, visto que os números de monografias e teses é 0.

A discussão de teses e artigos da instituição é importante para o desenvolvimento interno da instituição.

É necessário verificar se as teses e monografias estão sendo disponibilizadas de forma online.

Também é necessário investigar a razão da baixa taxa de empréstimo das coleções e Obras Raras.

In [39]:
gera_tabela_frequencia('biblioteca')

                                           biblioteca  quantidade  percentual
0                      Biblioteca Central Zila Mamede     1426122        68.8
1   Biblioteca Setorial do Centro Ciências da Saúd...      118614         5.7
2   Biblioteca Setorial da Faculdade de Ciências d...       77609         3.7
3   Biblioteca Setorial Prof. Alberto Moreira Camp...       66447         3.2
4   Biblioteca Setorial Profª. Maria Lúcia da Cost...       61478         3.0
5   Biblioteca Setorial Bertha Cruz Enders - ­Esco...       46040         2.2
6   Biblioteca Setorial do Centro de Ciências Huma...       40744         2.0
7   Biblioteca Setorial Dr. Paulo Bezerra - EMCM/R...       32097         1.5
8   Biblioteca Setorial Profª. Maria José Mamede G...       29089         1.4
9   Biblioteca Setorial Prof. Rodolfo Helinski - E...       27219         1.3
10  Biblioteca Setorial Prof. Francisco Gurgel De ...       26923         1.3
11  Biblioteca Setorial do Núcleo de Educação da I...       23656         1.1
12  Biblioteca Setorial Prof. Ronaldo Xavier de Ar...       22749         1.1
13  Biblioteca Setorial Pe. Jaime Diniz - Escola d...       21476         1.0
14  Biblioteca Setorial do Departamento de Artes -...       17099         0.8
15  Biblioteca Setorial Prof. Leopoldo Nelson - ­C...       12900         0.6
16  Biblioteca Setorial do Centro Ciências Sociais...       10533         0.5
17  Biblioteca Setorial Prof. Dr. Marcelo Bezerra ...        5057         0.2
18  Biblioteca Setorial Prof. Horácio Nicolas Soli...        4098         0.2
19            Biblioteca Setorial Moacyr de Góes - CE        1036         0.0
20  Biblioteca Setorial Árvore do Conhecimento - I...         919         0.0
21  Biblioteca Setorial do Núcleo de Ensino Superi...         617         0.0

Pelo tamanho da biblioteca faz sentido sua maior predominância.

Essa tabela é importante para entender o contexto geral das bibliotecas, porém para enriquecer a análise é necessária uma avalição interna de outras métricas:

* Investimento em cada biblioteca.
* Quantidade de empréstimos por usuário cadastrado na biblioteca.
* Quantidade de empréstimos esperada por cada biblioteca.

In [40]:
gera_tabela_frequencia('classe_CDU')

                              classe_CDU  quantidade  percentual
0                     Ciências aplicadas     1425473        68.8
1                       Ciências Sociais      369536        17.8
2         Matemática e ciências naturais       68744         3.3
3                               Religião       62295         3.0
4  Generalidades. Ciência e conhecimento       61767         3.0
5                 Filosofia e psicologia       60563         2.9
6         Geografia. Biografia. História        7989         0.4
7                            Belas artes        7911         0.4
8         Linguagem. Língua. Linguística        7490         0.4
9                            Classe vaga           0         0.0

É possível perceber uma grande diferença entre os temas.

É necessário verificar os temas de Geografia/Biografia/História devido a baixa frequência. Alguns questionamentos surgem:

* O Acervo está atualizado?
* O público tem necessidade desses temas? Se sim, porquê não estão usando?
* Quais ações de marketing estão sendo feitas nesses temas?

DIA 05

Desenvolver estratégias para o uso da informação é uma tarefa constante, devido às diversas mudanças que ocorrem o tempo todo: os usuários estão evoluindo seus conhecimentos, novos alunos chegam, alunos que se formam saem e as informações estão sempre em movimento e transformação.

Por este motivo, é importante realizar avaliações constantes do uso da biblioteca e entender em quais cenários (tipos de usuários, estratégias de marketing, atualização de acervo, cenário sócio-político interno e externo) é melhor manter a estratégia atual ou mudá-la.

Você vai fazer dois recortes em seus dados para entender como eles se distribuíram ao decorrer desses anos e, desta forma, possa trazer inferências para levar à diretoria da biblioteca, a fim de que eles possam tomar decisões para o ano atual.

Para isso, você vai avaliar dentre os alunos de graduação e pós graduação a distribuição de empréstimos mensais por ano realizados entre 2010 e 2020 da coleção que tiver a maior frequência de empréstimos.

Plote um gráfico para cada tipo de usuário. Tenha um boxplots para cada ano e analise o que ocorreu.

O que está ocorrendo ao decorrer do tempo? Houve algum ano ou anos em específico que te chamaram atenção para alguma diferença? Quais as maiores diferenças entre os empréstimos para os alunos de graduação e pós graduação?

* Verifique qual é a coleção com maior frequência para cada tipo de usuário.
* Filtre os dados com condições solicitadas
* Selecione apenas os empréstimos
* Faça a contagem de empréstimos mensais por cada ano
* Crie uma função para gerar a visualização do gráfico de box plot por cada ano.
* Crie o gráfico de boxplot

Verificando colecao com maior frequencia para cada tipo de usuário

In [41]:
df_emprestimos_completo.head(2)

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,classe_CDU
0,709684,L095049,NaT,2010-01-04 07:44:10.721,2010-01-05 16:26:12.662,2008023265.0,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,Ciências aplicadas
1,709685,L167050,NaT,2010-01-04 07:44:10.750,2010-01-12 07:34:13.934,2008023265.0,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,Ciências aplicadas

In [42]:
alunos_graduacao = df_emprestimos_completo.query('tipo_vinculo_usuario == "ALUNO DE GRADUAÇÃO"')
alunos_graduacao.value_counts('colecao').reset_index()

                                  colecao    count
0                       Acervo Circulante  1600155
1                              Multimeios     4652
2                             Monografias     3572
3                            Dissertações     1152
4                     Obras de Referência     1047
5            Publicações de Autores do RN      595
6                     Publicações da UFRN      466
7                                   Teses      245
8                                Folhetos      180
9                      Trabalho Acadêmico       81
10  Necessidades Educacionais Específicas       73
11                                Eventos       57
12                    Coleção Mossoroense       17
13                    Coleção Zila Mamede       15
14                   Literatura de Cordel       11
15                            Obras Raras        6

Criando a tabela com a quantidade mensal por ano

In [43]:
alunos_graduacao_acervo_circulante = alunos_graduacao.query('colecao == "Acervo Circulante"') #Filtro de coleção
alunos_graduacao_acervo_circulante = pd.DataFrame(alunos_graduacao_acervo_circulante)
alunos_graduacao_acervo_circulante['ano'] = alunos_graduacao_acervo_circulante['data_emprestimo'].dt.year
alunos_graduacao_acervo_circulante['mes'] = alunos_graduacao_acervo_circulante['data_emprestimo'].dt.month
alunos_graduacao_acervo_circulante = alunos_graduacao_acervo_circulante[['ano','mes']] #atribuição à tabela
alunos_graduacao_acervo_circulante = alunos_graduacao_acervo_circulante.value_counts().to_frame('quantidade').reset_index()
alunos_graduacao_acervo_circulante

      ano  mes  quantidade
0    2012    3       22797
1    2015    3       22483
2    2013    4       21853
3    2017    3       21735
4    2016    3       21692
..    ...  ...         ...
118  2016    1        2670
119  2019    1        2276
120  2019   12        1980
121  2020    1        1781
122  2011    1         809

[123 rows x 3 columns]

Função de geração do gráfico tipo box, usando plotly express.

In [44]:
def plota_grafico_box(dataset, x, y, titulo, subtitulo):
    '''
    Função que plota gráficos do tipo boxplot utilizando plotly express.
    Args:
    dataset: dataset contendo os dados para plotagem.
    x: valores do eixo x.
    y: valores do eixo y.
    titulo: título do gráfico.
    subtitulo: subtítulo do gráfico.
    Returns:
    None.
    '''
    fig = px.box(
        dataset,
        x = x,
        y = y,
        title = titulo,
        subtitle = subtitulo
    )
    fig.update_layout(
        xaxis = {
            'tickmode': 'linear',
            'title': None,
        },
        yaxis = {
            'title': None
        }
    )
    fig.show()

In [45]:
plota_grafico_box(alunos_graduacao_acervo_circulante, 'ano', 'quantidade','Distribuição de empréstimos mensais', 'realizados pelos alunos de graduação no acervo circulante.' )

É importante ressaltar que esse recorte, reflete grande parte da estrutura geral do conjunto de dados, pois são os tipos de usuários com maior frequência (alunos de graduação) e da coleção mais utilizada por eles (acervo circulante).

Com o boxplot é possível observar a oscilação da quantidade de empréstimos realizados mensalmente durante cada ano.

Além da análise geral realizada (declínio a partir de 2013, forte baixa em 2019), chama atenção os anos de 2014 e 2017. Que se excluíssemos os outliers (possivelmente meses de janeiro e dezembro) teríamos anos com uma quantidade constante de empréstimos mensais.

Mas se diferenciam principalmente porque em 2014 houve um declínio e em 2017 houve um aumento, em relação aos anos anteriores. Seria interessante entender com a direção das bibliotecas o que ocorreu nessas datas para que pudéssemos ter um contexto melhor da realidade do negócio.

Agora para os alunos de pós graduação

In [46]:
alunos_pos_graduacao = df_emprestimos_completo.query('tipo_vinculo_usuario == "ALUNO DE PÓS-GRADUAÇÃO"')
alunos_pos_graduacao.value_counts('colecao').reset_index()

                                  colecao   count
0                       Acervo Circulante  299201
1                            Dissertações     934
2                     Obras de Referência     700
3                              Multimeios     559
4                                   Teses     367
5                             Monografias     278
6            Publicações de Autores do RN     204
7                     Publicações da UFRN     121
8                                Folhetos      60
9   Necessidades Educacionais Específicas      30
10                                Eventos      26
11                    Coleção Mossoroense      23
12                     Trabalho Acadêmico      23
13                    Coleção Zila Mamede      11
14                   Literatura de Cordel       4

In [47]:
alunos_pos_graduacao_acervo_circulante = alunos_pos_graduacao.query('colecao == "Acervo Circulante"')
alunos_pos_graduacao_acervo_circulante = pd.DataFrame(alunos_pos_graduacao_acervo_circulante)
alunos_pos_graduacao_acervo_circulante['ano'] = alunos_pos_graduacao_acervo_circulante['data_emprestimo'].dt.year
alunos_pos_graduacao_acervo_circulante['mes'] = alunos_pos_graduacao_acervo_circulante['data_emprestimo'].dt.month
alunos_pos_graduacao_acervo_circulante = alunos_pos_graduacao_acervo_circulante[['ano','mes']]
alunos_pos_graduacao_acervo_circulante = alunos_pos_graduacao_acervo_circulante.value_counts().to_frame('quantidade').reset_index()
alunos_pos_graduacao_acervo_circulante

      ano  mes  quantidade
0    2015    3        3927
1    2017    8        3837
2    2017    3        3722
3    2016    3        3711
4    2016    8        3662
..    ...  ...         ...
119  2020    1        1143
120  2010    1        1105
121  2019   12        1069
122  2011    1         465
123  2020    6           2

[124 rows x 3 columns]

In [48]:
plota_grafico_box(alunos_pos_graduacao_acervo_circulante, 'ano', 'quantidade','Distribuição de empréstimos mensais', 'realizados pelos alunos de pós graduação no acervo circulante.' )

Já os alunos de pós graduação tiveram um aspecto diferente em relação ao declínio a partir de 2013:

A linha mediana foi diminuindo devagar até 2018. Entretanto valores máximos foram superiores, apenas caindo de fato em 2019. Nos dois gráficos podemos observar um grande aumento entre 2010 e 2013, o que nos leva a pensar em quais procedimentos estavam sendo realizados neste período para que houvesse esse crescimento.

Nos dois recortes visualizamos que a partir de 2018 tivemos um forte declínio e é um alerta para que a direção possa entender o que está ocorrendo.

DIA 06

Hoje, você terá mais dados para enriquecer as suas análises.

As instituições de ensino superior (IES) têm a necessidade de passar por avaliações do Ministério da Educação (MEC) para que possam ofertar e continuar ofertando cursos de graduação e pós-graduação.

A biblioteca universitária faz parte de um dos indicadores da avaliação dos cursos, em principalmente três aspectos: acervo, infraestrutura e serviços.

Dentre os serviços, são avaliados se existem recursos de bases referenciais para pesquisa, se há treinamentos para os usuários utilizarem os materiais, e a presença de indicadores sobre o uso dos materiais do acervo (empréstimos, consultas) dentre outros tópicos.

Durante meu trabalho como bibliotecário universitário, eu já passei por esta experiência, e um dos indicadores enviados foi a quantidade de empréstimos realizados nos últimos anos pelos cursos que seriam avaliados.

Por este motivo, no desafio de hoje, você precisará de novas métricas em relação aos empréstimos, de acordo com os cursos.

Você precisará calcular a quantidade de empréstimos realizados entre 2015 e 2020 por cada curso de graduação que passará pela avaliação.

Os cursos serão:

Biblioteconomia Ciências sociais Comunicação social Direito Filosofia Pedagogia

A universidade forneceu os dados dos usuários, mas uma parte deles está em planilhas de Excel, a outra parte veio através de uma API do sistema em formato JSON.

Extraia os dados destes arquivos, agrupe-os em apenas um só, e verifique depois a quantidade de empréstimos.

Gere uma tabela com as seguintes características:

Índice: Cursos Colunas: Ano Valores: Quantidade de empréstimos Total: Acrescente uma linha e uma coluna de total a tabela

In [49]:
caminho_do_arquivo = 'F:/Programação/Desafio-7-days-of-coding-dashboard/datasets/matricula_alunos.xlsx'
cadastro_alunos_antes_2010 = pd.read_excel(caminho_do_arquivo, sheet_name= 'Até 2010', skiprows= 1)
cadastro_alunos_apos_2010 = pd.read_excel(caminho_do_arquivo, sheet_name= 'Após 2010', skiprows= 1)

In [50]:
cadastro_alunos_antes_2010.head()

   Número da matrícula     Tipo de vinculo                Curso
0          190001688.0  ALUNO DE GRADUAÇÃO           MATEMÁTICA
1          199014489.0  ALUNO DE GRADUAÇÃO  CIÊNCIAS BIOLÓGICAS
2          199735674.0  ALUNO DE GRADUAÇÃO           MATEMÁTICA
3          199812431.0  ALUNO DE GRADUAÇÃO               LETRAS
4          199823670.0  ALUNO DE GRADUAÇÃO             ECOLOGIA

Renomeando colunas para o padrão

In [51]:
cadastro_alunos_antes_2010.columns = ['matricula_ou_siape', 'tipo_vinculo_usuario', 'curso']
cadastro_alunos_antes_2010

,matricula_ou_siape,tipo_vinculo_usuario,curso
0,1.900017e+08,ALUNO DE GRADUAÇÃO,MATEMÁTICA
1,1.990145e+08,ALUNO DE GRADUAÇÃO,CIÊNCIAS BIOLÓGICAS
2,1.997357e+08,ALUNO DE GRADUAÇÃO,MATEMÁTICA
3,1.998124e+08,ALUNO DE GRADUAÇÃO,LETRAS
4,1.998237e+08,ALUNO DE GRADUAÇÃO,ECOLOGIA
...,...,...,...
7721,2.009075e+09,ALUNO DE GRADUAÇÃO,BIBLIOTECONOMIA
7722,2.009075e+09,ALUNO DE GRADUAÇÃO,ANÁLISE E DESENVOLVIMENTO DE SISTEMAS
7723,2.009075e+09,ALUNO DE GRADUAÇÃO,ADMINISTRAÇÃO
7724,2.009075e+09,ALUNO DE GRADUAÇÃO,MÚSICA
7725,2.009075e+09,ALUNO DE GRADUAÇÃO,DIREITO

Mesmo processo para pós 2010

In [52]:
cadastro_alunos_apos_2010.columns = ['matricula_ou_siape', 'tipo_vinculo_usuario', 'curso']
cadastro_alunos_apos_2010

      matricula_ou_siape tipo_vinculo_usuario                     curso
0           2.010000e+09   ALUNO DE GRADUAÇÃO                   DIREITO
1           2.010000e+09   ALUNO DE GRADUAÇÃO                 AGRONOMIA
2           2.010001e+09   ALUNO DE GRADUAÇÃO        ENGENHARIA QUÍMICA
3           2.010003e+09   ALUNO DE GRADUAÇÃO      ENGENHARIA AMBIENTAL
4           2.010003e+09   ALUNO DE GRADUAÇÃO                 GEOGRAFIA
...                  ...                  ...                       ...
2269        2.015012e+10   ALUNO DE GRADUAÇÃO                    LETRAS
2270        2.015075e+09   ALUNO DE GRADUAÇÃO                     DANÇA
2271        2.016000e+10   ALUNO DE GRADUAÇÃO  ENGENHARIA DA COMPUTAÇÃO
2272        2.017009e+10   ALUNO DE GRADUAÇÃO           BIBLIOTECONOMIA
2273        2.018009e+10   ALUNO DE GRADUAÇÃO                     DANÇA

[2274 rows x 3 columns]

Juntando os arquivos em um só.

In [53]:
cadastro_usuarios_excel = pd.concat([cadastro_alunos_antes_2010, cadastro_alunos_apos_2010], ignore_index= True)
cadastro_usuarios_excel

      matricula_ou_siape tipo_vinculo_usuario                     curso
0           1.900017e+08   ALUNO DE GRADUAÇÃO                MATEMÁTICA
1           1.990145e+08   ALUNO DE GRADUAÇÃO       CIÊNCIAS BIOLÓGICAS
2           1.997357e+08   ALUNO DE GRADUAÇÃO                MATEMÁTICA
3           1.998124e+08   ALUNO DE GRADUAÇÃO                    LETRAS
4           1.998237e+08   ALUNO DE GRADUAÇÃO                  ECOLOGIA
...                  ...                  ...                       ...
9995        2.015012e+10   ALUNO DE GRADUAÇÃO                    LETRAS
9996        2.015075e+09   ALUNO DE GRADUAÇÃO                     DANÇA
9997        2.016000e+10   ALUNO DE GRADUAÇÃO  ENGENHARIA DA COMPUTAÇÃO
9998        2.017009e+10   ALUNO DE GRADUAÇÃO           BIBLIOTECONOMIA
9999        2.018009e+10   ALUNO DE GRADUAÇÃO                     DANÇA

[10000 rows x 3 columns]

In [54]:
cadastro_usuarios_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   matricula_ou_siape    10000 non-null  float64
 1   tipo_vinculo_usuario  10000 non-null  object
 2   curso                 10000 non-null  object
dtypes: float64(1), object(2)
memory usage: 234.5+ KB

In [55]:
cadastro_usuarios_excel.matricula_ou_siape = cadastro_usuarios_excel.matricula_ou_siape.astype('string')
cadastro_usuarios_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   matricula_ou_siape    10000 non-null  string
 1   tipo_vinculo_usuario  10000 non-null  object
 2   curso                 10000 non-null  object
dtypes: object(2), string(1)
memory usage: 234.5+ KB

Adicionanado arquivo JSON

In [56]:
cadastro_usuarios_json = pd.read_json('F:/Programação/Desafio-7-days-of-coding-dashboard/datasets/dataset_cadastro_alunos/cadastro_alunos.json')
cadastro_usuarios_json

     tipo_curso                                          registros
0     GRADUACAO  [{"matricula_ou_siape": "2009029003.0", "tipo_...
1  POSGRADUACAO  [{"matricula_ou_siape": "2008112114.0", "tipo_...

Devemos acessar os alunos de graduação, logo:

In [57]:
from io import StringIO
cadastro_usuarios_graduacao = pd.read_json(StringIO(cadastro_usuarios_json.registros[0]))
cadastro_usuarios_graduacao

       matricula_ou_siape tipo_vinculo_usuario                   curso
0              2009029003   ALUNO DE GRADUAÇÃO               FILOSOFIA
1               200617346   ALUNO DE GRADUAÇÃO                 DIREITO
2               200746502   ALUNO DE GRADUAÇÃO  ENGENHARIA DE PETRÓLEO
3               200504968   ALUNO DE GRADUAÇÃO           ADMINISTRAÇÃO
4               200615572   ALUNO DE GRADUAÇÃO   CIÊNCIA DA COMPUTAÇÃO
...                   ...                  ...                     ...
62797         20200012706   ALUNO DE GRADUAÇÃO         BIBLIOTECONOMIA
62798         20200039601   ALUNO DE GRADUAÇÃO    ENGENHARIA FLORESTAL
62799         20200132517   ALUNO DE GRADUAÇÃO               AGRONOMIA
62800         20200009344   ALUNO DE GRADUAÇÃO         BIBLIOTECONOMIA
62801         20200090284   ALUNO DE GRADUAÇÃO                 DIREITO

[62802 rows x 3 columns]

In [58]:
cadastro_usuarios_graduacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62802 entries, 0 to 62801
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   matricula_ou_siape    62802 non-null  int64
 1   tipo_vinculo_usuario  62802 non-null  object
 2   curso                 62802 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.4+ MB

In [59]:
cadastro_usuarios_graduacao.matricula_ou_siape = cadastro_usuarios_graduacao.matricula_ou_siape.astype('float')
cadastro_usuarios_graduacao.matricula_ou_siape = cadastro_usuarios_graduacao.matricula_ou_siape.astype('string')
cadastro_usuarios_graduacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62802 entries, 0 to 62801
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   matricula_ou_siape    62802 non-null  string
 1   tipo_vinculo_usuario  62802 non-null  object
 2   curso                 62802 non-null  object
dtypes: object(2), string(1)
memory usage: 1.4+ MB

Juntando os dois datasets

In [60]:
cadastro_usuario_curso = pd.concat([cadastro_usuarios_excel, cadastro_usuarios_graduacao], ignore_index= True)
cadastro_usuario_curso

      matricula_ou_siape tipo_vinculo_usuario                 curso
0            190001688.0   ALUNO DE GRADUAÇÃO            MATEMÁTICA
1            199014489.0   ALUNO DE GRADUAÇÃO   CIÊNCIAS BIOLÓGICAS
2            199735674.0   ALUNO DE GRADUAÇÃO            MATEMÁTICA
3            199812431.0   ALUNO DE GRADUAÇÃO                LETRAS
4            199823670.0   ALUNO DE GRADUAÇÃO              ECOLOGIA
...                  ...                  ...                   ...
72797      20200012706.0   ALUNO DE GRADUAÇÃO       BIBLIOTECONOMIA
72798      20200039601.0   ALUNO DE GRADUAÇÃO  ENGENHARIA FLORESTAL
72799      20200132517.0   ALUNO DE GRADUAÇÃO             AGRONOMIA
72800      20200009344.0   ALUNO DE GRADUAÇÃO       BIBLIOTECONOMIA
72801      20200090284.0   ALUNO DE GRADUAÇÃO               DIREITO

[72802 rows x 3 columns]

Empréstimo dos alunos de graduação de 2015 em diante

In [61]:
matricula_data_emprestimo = df_emprestimos_completo.query('tipo_vinculo_usuario == "ALUNO DE GRADUAÇÃO"')
matricula_data_emprestimo = matricula_data_emprestimo.loc[:,['matricula_ou_siape','data_emprestimo']]
matricula_data_emprestimo.data_emprestimo = pd.to_datetime(matricula_data_emprestimo.data_emprestimo)
matricula_data_emprestimo = matricula_data_emprestimo.query('data_emprestimo > "2015"')
matricula_data_emprestimo = matricula_data_emprestimo.reset_index(drop=True)
matricula_data_emprestimo

       matricula_ou_siape         data_emprestimo
0            2013021576.0 2015-01-02 09:16:49.566
1            2014026648.0 2015-01-02 09:44:42.808
2            2014026648.0 2015-01-02 09:44:43.127
3            2010049586.0 2015-01-02 10:11:09.837
4            2014021454.0 2015-01-02 10:19:38.087
...                   ...                     ...
788099      20190154579.0 2020-03-18 16:26:20.477
788100      20160129109.0 2020-03-18 16:41:28.500
788101      20160129109.0 2020-03-18 16:41:28.588
788102      20160129109.0 2020-03-18 16:41:28.662
788103      20160129109.0 2020-03-18 16:41:28.713

[788104 rows x 2 columns]

Contando e excluindo valores nulos

In [62]:
matricula_data_emprestimo.isnull().sum()

matricula_ou_siape    94
data_emprestimo        0
dtype: int64

In [63]:
matricula_data_emprestimo = matricula_data_emprestimo.dropna()

Filtrando por curso selecionado

In [64]:
cadastro_usuarios_cursos_selecionados = cadastro_usuario_curso.query("curso == ['BIBLIOTECONOMIA','CIÊNCIAS SOCIAIS','COMUNICAÇÃO SOCIAL','DIREITO','FILOSOFIA','PEDAGOGIA']")
cadastro_usuarios_cursos_selecionados

      matricula_ou_siape tipo_vinculo_usuario             curso
8            200031011.0   ALUNO DE GRADUAÇÃO           DIREITO
9            200045080.0   ALUNO DE GRADUAÇÃO   BIBLIOTECONOMIA
15           200115053.0   ALUNO DE GRADUAÇÃO  CIÊNCIAS SOCIAIS
18           200123382.0   ALUNO DE GRADUAÇÃO   BIBLIOTECONOMIA
19           200123730.0   ALUNO DE GRADUAÇÃO   BIBLIOTECONOMIA
...                  ...                  ...               ...
72789      20200097481.0   ALUNO DE GRADUAÇÃO         PEDAGOGIA
72796      20200107087.0   ALUNO DE GRADUAÇÃO         PEDAGOGIA
72797      20200012706.0   ALUNO DE GRADUAÇÃO   BIBLIOTECONOMIA
72800      20200009344.0   ALUNO DE GRADUAÇÃO   BIBLIOTECONOMIA
72801      20200090284.0   ALUNO DE GRADUAÇÃO           DIREITO

[18833 rows x 3 columns]

Agora unindo os datasets de cursos selecionados com empréstimos

In [65]:
cadastro_usuarios_cursos_selecionados = matricula_data_emprestimo.merge(cadastro_usuarios_cursos_selecionados)
cadastro_usuarios_cursos_selecionados

,matricula_ou_siape,data_emprestimo,tipo_vinculo_usuario,curso
0,2014021454.0,2015-01-02 10:19:38.087,ALUNO DE GRADUAÇÃO,FILOSOFIA
1,2013018187.0,2015-01-02 10:25:40.883,ALUNO DE GRADUAÇÃO,DIREITO
2,2014029499.0,2015-01-02 12:26:43.571,ALUNO DE GRADUAÇÃO,CIÊNCIAS SOCIAIS
3,2014029499.0,2015-01-02 12:26:43.840,ALUNO DE GRADUAÇÃO,CIÊNCIAS SOCIAIS
4,2014029499.0,2015-01-02 12:26:44.750,ALUNO DE GRADUAÇÃO,CIÊNCIAS SOCIAIS
...,...,...,...,...
212833,20200090284.0,2020-03-17 20:23:54.966,ALUNO DE GRADUAÇÃO,DIREITO
212834,20180113385.0,2020-03-17 21:20:47.278,ALUNO DE GRADUAÇÃO,CIÊNCIAS SOCIAIS
212835,20190150079.0,2020-03-18 13:43:53.220,ALUNO DE GRADUAÇÃO,PEDAGOGIA
212836,20190150079.0,2020-03-18 13:43:53.389,ALUNO DE GRADUAÇÃO,PEDAGOGIA
212837,20190150079.0,2020-03-18 13:43:53.456,ALUNO DE GRADUAÇÃO,PEDAGOGIA

Gerando nova tabela

In [66]:
cadastro_usuarios_cursos_selecionados['data_emprestimo'] = cadastro_usuarios_cursos_selecionados['data_emprestimo'].dt.year

In [67]:
cadastro_usuarios_cursos_selecionados

,matricula_ou_siape,data_emprestimo,tipo_vinculo_usuario,curso
0,2014021454.0,2015,ALUNO DE GRADUAÇÃO,FILOSOFIA
1,2013018187.0,2015,ALUNO DE GRADUAÇÃO,DIREITO
2,2014029499.0,2015,ALUNO DE GRADUAÇÃO,CIÊNCIAS SOCIAIS
3,2014029499.0,2015,ALUNO DE GRADUAÇÃO,CIÊNCIAS SOCIAIS
4,2014029499.0,2015,ALUNO DE GRADUAÇÃO,CIÊNCIAS SOCIAIS
...,...,...,...,...
212833,20200090284.0,2020,ALUNO DE GRADUAÇÃO,DIREITO
212834,20180113385.0,2020,ALUNO DE GRADUAÇÃO,CIÊNCIAS SOCIAIS
212835,20190150079.0,2020,ALUNO DE GRADUAÇÃO,PEDAGOGIA
212836,20190150079.0,2020,ALUNO DE GRADUAÇÃO,PEDAGOGIA
212837,20190150079.0,2020,ALUNO DE GRADUAÇÃO,PEDAGOGIA

In [68]:
emprestimo_cursos_selecionados = cadastro_usuarios_cursos_selecionados.iloc[:,[1,3]].value_counts().reset_index()
emprestimo_cursos_selecionados.columns = ['ANO', 'CURSO', 'QUANTIDADE']
emprestimo_cursos_selecionados

     ANO               CURSO  QUANTIDADE
0   2017  COMUNICAÇÃO SOCIAL        8253
1   2016  COMUNICAÇÃO SOCIAL        7973
2   2017             DIREITO        7885
3   2015     BIBLIOTECONOMIA        7784
4   2015             DIREITO        7665
5   2016           FILOSOFIA        7576
6   2015    CIÊNCIAS SOCIAIS        7489
7   2017           PEDAGOGIA        7434
8   2017           FILOSOFIA        7389
9   2016             DIREITO        7363
10  2017     BIBLIOTECONOMIA        7307
11  2015           PEDAGOGIA        7189
12  2016           PEDAGOGIA        7153
13  2015  COMUNICAÇÃO SOCIAL        7147
14  2016     BIBLIOTECONOMIA        7044
15  2018             DIREITO        7027
16  2016    CIÊNCIAS SOCIAIS        6978
17  2018  COMUNICAÇÃO SOCIAL        6953
18  2015           FILOSOFIA        6950
19  2017    CIÊNCIAS SOCIAIS        6918
20  2018           PEDAGOGIA        6518
21  2018     BIBLIOTECONOMIA        6378
22  2018           FILOSOFIA        6296
23  2018    CIÊNCIAS SOCIAIS        6181
24  2019     BIBLIOTECONOMIA        5889
25  2019  COMUNICAÇÃO SOCIAL        5885
26  2019           PEDAGOGIA        5869
27  2019             DIREITO        5861
28  2019    CIÊNCIAS SOCIAIS        5788
29  2019           FILOSOFIA        5572
30  2020             DIREITO         905
31  2020     BIBLIOTECONOMIA         900
32  2020           PEDAGOGIA         866
33  2020           FILOSOFIA         832
34  2020    CIÊNCIAS SOCIAIS         825
35  2020  COMUNICAÇÃO SOCIAL         796

Pivotando a coluna

In [69]:
emprestimo_cursos_selecionados_pivot = emprestimo_cursos_selecionados.pivot_table(
    index = 'CURSO',
    values = 'QUANTIDADE',
    columns = 'ANO',
    fill_value ='-',
    aggfunc = 'sum',
    margins = True,
    margins_name = 'TOTAL'
)
emprestimo_cursos_selecionados_pivot.reset_index()
emprestimo_cursos_selecionados_pivot

ANO                  2015   2016   2017   2018   2019  2020   TOTAL
CURSO
BIBLIOTECONOMIA      7784   7044   7307   6378   5889   900   35302
CIÊNCIAS SOCIAIS     7489   6978   6918   6181   5788   825   34179
COMUNICAÇÃO SOCIAL   7147   7973   8253   6953   5885   796   37007
DIREITO              7665   7363   7885   7027   5861   905   36706
FILOSOFIA            6950   7576   7389   6296   5572   832   34615
PEDAGOGIA            7189   7153   7434   6518   5869   866   35029
TOTAL               44224  44087  45186  39353  34864  5124  212838

DIA 07

Olá, Wyndam

Esse é o seu último dia de #7DaysOfCode com Python Pandas! Durante os últimos 6 dias, você percorreu uma jornada com desafios diários com os quais você pode praticar bastante as suas habilidades.

Você brincou com conceitos de importação de diferentes formatos, manipulação e limpeza, exploração e visualização.

Tenho muito orgulho que você chegou até aqui! Agora vamos finalizar com mais um desafio?

A diretoria da biblioteca está montando um plano de ação de marketing focado nos alunos da pós-graduação. Para isso, precisará analisar a diferença percentual de empréstimos realizados nos últimos anos (2017, 2018, 2019) para cada curso.

Devido à pandemia do COVID-19, ela não poderá utilizar os dados de 2020 e 2021. Entretanto, seu colega de equipe já realizou uma análise de previsão de empréstimos de 2022 e a disponibilizou para que você também possa realizar o comparativo entre 2019-2022.

Você precisará criar uma tabela com as diferenças percentuais de empréstimos entre 2017-2018, 2018-2019, 2019-2022.

Porém, essa análise será disponibilizada em conjunto com outros dados, através de uma página da web, e a equipe de Front-end te solicitou que enviassem para eles o HTML da tabela.

Eles precisam que ela tenha as seguintes características:

Não contenha numeração de índice;

Os nomes dos cursos tenham apenas a primeira letra maiúscula;

Os números percentuais estejam indicados pelo símbolo “%”;

Cor dos números: Positivos = Verde; Negativos = Vermelho

In [70]:
cadastro_usuarios_excel

     matricula_ou_siape tipo_vinculo_usuario                     curso
0           190001688.0   ALUNO DE GRADUAÇÃO                MATEMÁTICA
1           199014489.0   ALUNO DE GRADUAÇÃO       CIÊNCIAS BIOLÓGICAS
2           199735674.0   ALUNO DE GRADUAÇÃO                MATEMÁTICA
3           199812431.0   ALUNO DE GRADUAÇÃO                    LETRAS
4           199823670.0   ALUNO DE GRADUAÇÃO                  ECOLOGIA
...                 ...                  ...                       ...
9995      20150116770.0   ALUNO DE GRADUAÇÃO                    LETRAS
9996       2015074523.0   ALUNO DE GRADUAÇÃO                     DANÇA
9997      20160002745.0   ALUNO DE GRADUAÇÃO  ENGENHARIA DA COMPUTAÇÃO
9998      20170086533.0   ALUNO DE GRADUAÇÃO           BIBLIOTECONOMIA
9999      20180090351.0   ALUNO DE GRADUAÇÃO                     DANÇA

[10000 rows x 3 columns]

In [71]:
cadastro_usuarios_json

     tipo_curso                                          registros
0     GRADUACAO  [{"matricula_ou_siape": "2009029003.0", "tipo_...
1  POSGRADUACAO  [{"matricula_ou_siape": "2008112114.0", "tipo_...

In [72]:
cadastro_usuarios_pos_graduacao = pd.read_json(StringIO(cadastro_usuarios_json.registros[1]))
cadastro_usuarios_pos_graduacao

,matricula_ou_siape,tipo_vinculo_usuario,curso
0,2008112114,ALUNO DE PÓS-GRADUAÇÃO,CIÊNCIAS ODONTOLÓGICAS
1,2008106583,ALUNO DE PÓS-GRADUAÇÃO,ENGENHARIA DE SOFTWARE
2,2011101417,ALUNO DE PÓS-GRADUAÇÃO,ARQUITETURA E URBANISMO
3,2011113122,ALUNO DE PÓS-GRADUAÇÃO,FILOSOFIA
4,2010110903,ALUNO DE PÓS-GRADUAÇÃO,ARTES CÊNICAS
...,...,...,...
19435,20201013501,ALUNO DE PÓS-GRADUAÇÃO,GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO
19436,20201014062,ALUNO DE PÓS-GRADUAÇÃO,"CIÊNCIA, TECNOLOGIA E INOVAÇÃO"
19437,20201017690,ALUNO DE PÓS-GRADUAÇÃO,CIÊNCIAS DA SAÚDE
19438,20201014465,ALUNO DE PÓS-GRADUAÇÃO,DESIGN
19439,20201014993,ALUNO DE PÓS-GRADUAÇÃO,DESIGN

Convertendo a coluna matrícula

In [73]:
cadastro_usuarios_pos_graduacao.matricula_ou_siape = cadastro_usuarios_pos_graduacao.matricula_ou_siape.astype('float')
cadastro_usuarios_pos_graduacao.matricula_ou_siape = cadastro_usuarios_pos_graduacao.matricula_ou_siape.astype('string')
cadastro_usuarios_pos_graduacao

,matricula_ou_siape,tipo_vinculo_usuario,curso
0,2008112114.0,ALUNO DE PÓS-GRADUAÇÃO,CIÊNCIAS ODONTOLÓGICAS
1,2008106583.0,ALUNO DE PÓS-GRADUAÇÃO,ENGENHARIA DE SOFTWARE
2,2011101417.0,ALUNO DE PÓS-GRADUAÇÃO,ARQUITETURA E URBANISMO
3,2011113122.0,ALUNO DE PÓS-GRADUAÇÃO,FILOSOFIA
4,2010110903.0,ALUNO DE PÓS-GRADUAÇÃO,ARTES CÊNICAS
...,...,...,...
19435,20201013501.0,ALUNO DE PÓS-GRADUAÇÃO,GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO
19436,20201014062.0,ALUNO DE PÓS-GRADUAÇÃO,"CIÊNCIA, TECNOLOGIA E INOVAÇÃO"
19437,20201017690.0,ALUNO DE PÓS-GRADUAÇÃO,CIÊNCIAS DA SAÚDE
19438,20201014465.0,ALUNO DE PÓS-GRADUAÇÃO,DESIGN
19439,20201014993.0,ALUNO DE PÓS-GRADUAÇÃO,DESIGN

In [74]:
cadastro_usuarios_pos_graduacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19440 entries, 0 to 19439
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   matricula_ou_siape    19440 non-null  string
 1   tipo_vinculo_usuario  19440 non-null  object
 2   curso                 19440 non-null  object
dtypes: object(2), string(1)
memory usage: 455.8+ KB

In [75]:
cadastro_usuarios_cursos = pd.concat([cadastro_usuarios_excel, cadastro_usuarios_pos_graduacao], ignore_index= True)
cadastro_usuarios_cursos

,matricula_ou_siape,tipo_vinculo_usuario,curso
0,190001688.0,ALUNO DE GRADUAÇÃO,MATEMÁTICA
1,199014489.0,ALUNO DE GRADUAÇÃO,CIÊNCIAS BIOLÓGICAS
2,199735674.0,ALUNO DE GRADUAÇÃO,MATEMÁTICA
3,199812431.0,ALUNO DE GRADUAÇÃO,LETRAS
4,199823670.0,ALUNO DE GRADUAÇÃO,ECOLOGIA
...,...,...,...
29435,20201013501.0,ALUNO DE PÓS-GRADUAÇÃO,GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO
29436,20201014062.0,ALUNO DE PÓS-GRADUAÇÃO,"CIÊNCIA, TECNOLOGIA E INOVAÇÃO"
29437,20201017690.0,ALUNO DE PÓS-GRADUAÇÃO,CIÊNCIAS DA SAÚDE
29438,20201014465.0,ALUNO DE PÓS-GRADUAÇÃO,DESIGN
29439,20201014993.0,ALUNO DE PÓS-GRADUAÇÃO,DESIGN

Filtrando a pós graduação

In [76]:
cadastro_usuarios_cursos_pos_graduacao = cadastro_usuarios_cursos.query('tipo_vinculo_usuario == "ALUNO DE PÓS-GRADUAÇÃO"')
cadastro_usuarios_cursos_pos_graduacao

,matricula_ou_siape,tipo_vinculo_usuario,curso
10000,2008112114.0,ALUNO DE PÓS-GRADUAÇÃO,CIÊNCIAS ODONTOLÓGICAS
10001,2008106583.0,ALUNO DE PÓS-GRADUAÇÃO,ENGENHARIA DE SOFTWARE
10002,2011101417.0,ALUNO DE PÓS-GRADUAÇÃO,ARQUITETURA E URBANISMO
10003,2011113122.0,ALUNO DE PÓS-GRADUAÇÃO,FILOSOFIA
10004,2010110903.0,ALUNO DE PÓS-GRADUAÇÃO,ARTES CÊNICAS
...,...,...,...
29435,20201013501.0,ALUNO DE PÓS-GRADUAÇÃO,GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO
29436,20201014062.0,ALUNO DE PÓS-GRADUAÇÃO,"CIÊNCIA, TECNOLOGIA E INOVAÇÃO"
29437,20201017690.0,ALUNO DE PÓS-GRADUAÇÃO,CIÊNCIAS DA SAÚDE
29438,20201014465.0,ALUNO DE PÓS-GRADUAÇÃO,DESIGN
29439,20201014993.0,ALUNO DE PÓS-GRADUAÇÃO,DESIGN

Filtrando os empréstimos desde de 2017

In [77]:
matricula_data_emprestimo_pos_graduacao = df_emprestimos_completo.loc[:,['matricula_ou_siape','data_emprestimo']]
matricula_data_emprestimo_pos_graduacao = matricula_data_emprestimo_pos_graduacao.query('data_emprestimo > "2017"')
matricula_data_emprestimo_pos_graduacao = matricula_data_emprestimo_pos_graduacao.reset_index(drop=True)
matricula_data_emprestimo_pos_graduacao

       matricula_ou_siape         data_emprestimo
0            2014035816.0 2017-01-02 08:01:14.113
1           20161011168.0 2017-01-02 08:29:46.722
2           20161011168.0 2017-01-02 08:29:46.794
3           20161011168.0 2017-01-02 08:46:42.991
4           20161011168.0 2017-01-02 08:46:43.400
...                   ...                     ...
609948          3067431.0 2020-05-05 19:51:06.059
609949          3067431.0 2020-05-05 19:51:06.135
609950          3067431.0 2020-05-05 19:51:06.164
609951      20201014993.0 2020-06-09 11:54:02.669
609952      20201014993.0 2020-06-09 11:54:02.852

[609953 rows x 2 columns]

Unindo os datasets de cadastro de usuarios e de empréstimos

In [78]:
emprestimos_pos_graduacao_desde_2017 = matricula_data_emprestimo_pos_graduacao.merge(cadastro_usuarios_cursos_pos_graduacao)
emprestimos_pos_graduacao_desde_2017

,matricula_ou_siape,data_emprestimo,tipo_vinculo_usuario,curso
0,20161011168.0,2017-01-02 08:29:46.722,ALUNO DE PÓS-GRADUAÇÃO,FILOSOFIA
1,20161011168.0,2017-01-02 08:29:46.794,ALUNO DE PÓS-GRADUAÇÃO,FILOSOFIA
2,20161011168.0,2017-01-02 08:46:42.991,ALUNO DE PÓS-GRADUAÇÃO,FILOSOFIA
3,20161011168.0,2017-01-02 08:46:43.400,ALUNO DE PÓS-GRADUAÇÃO,FILOSOFIA
4,20161013903.0,2017-01-02 09:41:45.823,ALUNO DE PÓS-GRADUAÇÃO,DESIGN
...,...,...,...,...
92057,20191017055.0,2020-03-19 14:41:57.754,ALUNO DE PÓS-GRADUAÇÃO,ENGENHARIA CIVIL
92058,20191017055.0,2020-03-19 14:42:56.670,ALUNO DE PÓS-GRADUAÇÃO,ENGENHARIA CIVIL
92059,20191017055.0,2020-03-19 14:43:40.666,ALUNO DE PÓS-GRADUAÇÃO,ENGENHARIA CIVIL
92060,20201014993.0,2020-06-09 11:54:02.669,ALUNO DE PÓS-GRADUAÇÃO,DESIGN
92061,20201014993.0,2020-06-09 11:54:02.852,ALUNO DE PÓS-GRADUAÇÃO,DESIGN

In [79]:
emprestimos_pos_graduacao_desde_2017.data_emprestimo = emprestimos_pos_graduacao_desde_2017.data_emprestimo.dt.year

In [80]:
emprestimos_pos_graduacao_e_curso = emprestimos_pos_graduacao_desde_2017.iloc[:,[1,3]].value_counts().reset_index()
emprestimos_pos_graduacao_e_curso.columns = ['ANO','CURSO','QUANTIDADE']
emprestimos_pos_graduacao_e_curso

     ANO                                   CURSO  QUANTIDADE
0   2018                  CIÊNCIAS ODONTOLÓGICAS        2540
1   2017                           ADMINISTRAÇÃO        2538
2   2017                  ENGENHARIA DE SOFTWARE        2477
3   2017                       CIÊNCIAS DA SAÚDE        2434
4   2017          CIÊNCIA, TECNOLOGIA E INOVAÇÃO        2415
5   2017                  CIÊNCIAS ODONTOLÓGICAS        2414
6   2017                        ENGENHARIA CIVIL        2399
7   2018          CIÊNCIA, TECNOLOGIA E INOVAÇÃO        2365
8   2017       CIÊNCIA E ENGENHARIA DE MATERIAIS        2316
9   2018                           ADMINISTRAÇÃO        2316
10  2017                              BIOQUÍMICA        2294
11  2017                                  DESIGN        2272
12  2017  GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO        2266
13  2018                  ENGENHARIA DE SOFTWARE        2222
14  2017                 ARQUITETURA E URBANISMO        2209
15  2017                          BIOINFORMÁTICA        2190
16  2017                               FILOSOFIA        2170
17  2019                  CIÊNCIAS ODONTOLÓGICAS        2134
18  2017                           ARTES CÊNICAS        2115
19  2018       CIÊNCIA E ENGENHARIA DE MATERIAIS        2110
20  2018                        ENGENHARIA CIVIL        2089
21  2018                           ARTES CÊNICAS        2082
22  2019                              BIOQUÍMICA        2057
23  2018                               FILOSOFIA        2048
24  2019          CIÊNCIA, TECNOLOGIA E INOVAÇÃO        2026
25  2019       CIÊNCIA E ENGENHARIA DE MATERIAIS        2008
26  2019                        ENGENHARIA CIVIL        1989
27  2018                       CIÊNCIAS DA SAÚDE        1986
28  2018                              BIOQUÍMICA        1944
29  2018                 ARQUITETURA E URBANISMO        1917
30  2018                          BIOINFORMÁTICA        1914
31  2018  GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO        1891
32  2019                  ENGENHARIA DE SOFTWARE        1887
33  2019                                  DESIGN        1841
34  2018                                  DESIGN        1838
35  2019                          BIOINFORMÁTICA        1825
36  2019                       CIÊNCIAS DA SAÚDE        1825
37  2019                 ARQUITETURA E URBANISMO        1818
38  2019                           ARTES CÊNICAS        1812
39  2019                               FILOSOFIA        1773
40  2019  GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO        1771
41  2019                           ADMINISTRAÇÃO        1692
42  2020                  CIÊNCIAS ODONTOLÓGICAS         352
43  2020       CIÊNCIA E ENGENHARIA DE MATERIAIS         328
44  2020          CIÊNCIA, TECNOLOGIA E INOVAÇÃO         303
45  2020                               FILOSOFIA         302
46  2020                              BIOQUÍMICA         272
47  2020                           ADMINISTRAÇÃO         269
48  2020                  ENGENHARIA DE SOFTWARE         264
49  2020                          BIOINFORMÁTICA         263
50  2020                 ARQUITETURA E URBANISMO         257
51  2020                        ENGENHARIA CIVIL         254
52  2020                                  DESIGN         254
53  2020  GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO         252
54  2020                       CIÊNCIAS DA SAÚDE         234
55  2020                           ARTES CÊNICAS         229

Pivotando a tabela

In [81]:
emprestimos_pos_graduacao_e_curso_pivot = emprestimos_pos_graduacao_e_curso.pivot_table(
    index = 'CURSO',
    values = 'QUANTIDADE',
    columns = 'ANO'
)
emprestimos_pos_graduacao_e_curso_pivot.reset_index()
emprestimos_pos_graduacao_e_curso_pivot

ANO                                       2017    2018    2019   2020
CURSO
ADMINISTRAÇÃO                           2538.0  2316.0  1692.0  269.0
ARQUITETURA E URBANISMO                 2209.0  1917.0  1818.0  257.0
ARTES CÊNICAS                           2115.0  2082.0  1812.0  229.0
BIOINFORMÁTICA                          2190.0  1914.0  1825.0  263.0
BIOQUÍMICA                              2294.0  1944.0  2057.0  272.0
CIÊNCIA E ENGENHARIA DE MATERIAIS       2316.0  2110.0  2008.0  328.0
CIÊNCIA, TECNOLOGIA E INOVAÇÃO          2415.0  2365.0  2026.0  303.0
CIÊNCIAS DA SAÚDE                       2434.0  1986.0  1825.0  234.0
CIÊNCIAS ODONTOLÓGICAS                  2414.0  2540.0  2134.0  352.0
DESIGN                                  2272.0  1838.0  1841.0  254.0
ENGENHARIA CIVIL                        2399.0  2089.0  1989.0  254.0
ENGENHARIA DE SOFTWARE                  2477.0  2222.0  1887.0  264.0
FILOSOFIA                               2170.0  2048.0  1773.0  302.0
GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO  2266.0  1891.0  1771.0  252.0

Importando os dados de previsão

In [82]:
previsao_2022 = pd.read_table('F:/Programação/Desafio-7-days-of-coding-dashboard/datasets/dataset_previsao/previsao.txt')
previsao_2022

                            curso previsao_2022
0                            administracao 1905
1                  arquitetura_e_urbanismo 1896
2                            artes_cenicas 1920
3                           bioinformatica 2302
4                               bioquimica 2090
5        ciencia_e_engenharia_de_materiais 2010
6            ciencia_tecnologia_e_inovacao 1960
7                        ciencias_da_saude 1730
8                   ciencias_odontologicas 2405
9                                   design 1900
10                        engenharia_civil 1920
11                     engenharia_software 1890
12                               filosofia 1903
13  gestao_da_informacao_e_do_conhecimento 1855

In [83]:
previsao_2022 = previsao_2022['curso previsao_2022'].str.split(' ', expand = True)
previsao_2022

                                         0     1
0                            administracao  1905
1                  arquitetura_e_urbanismo  1896
2                            artes_cenicas  1920
3                           bioinformatica  2302
4                               bioquimica  2090
5        ciencia_e_engenharia_de_materiais  2010
6            ciencia_tecnologia_e_inovacao  1960
7                        ciencias_da_saude  1730
8                   ciencias_odontologicas  2405
9                                   design  1900
10                        engenharia_civil  1920
11                     engenharia_software  1890
12                               filosofia  1903
13  gestao_da_informacao_e_do_conhecimento  1855

Unindo as duas tabelas

In [84]:
previsao_2022.index = emprestimos_pos_graduacao_e_curso_pivot.index
emprestimos_pos_graduacao_e_curso_pivot['2022'] = previsao_2022.iloc[:,1]
emprestimos_pos_graduacao_e_curso_pivot

ANO                                       2017    2018    2019   2020  2022
CURSO
ADMINISTRAÇÃO                           2538.0  2316.0  1692.0  269.0  1905
ARQUITETURA E URBANISMO                 2209.0  1917.0  1818.0  257.0  1896
ARTES CÊNICAS                           2115.0  2082.0  1812.0  229.0  1920
BIOINFORMÁTICA                          2190.0  1914.0  1825.0  263.0  2302
BIOQUÍMICA                              2294.0  1944.0  2057.0  272.0  2090
CIÊNCIA E ENGENHARIA DE MATERIAIS       2316.0  2110.0  2008.0  328.0  2010
CIÊNCIA, TECNOLOGIA E INOVAÇÃO          2415.0  2365.0  2026.0  303.0  1960
CIÊNCIAS DA SAÚDE                       2434.0  1986.0  1825.0  234.0  1730
CIÊNCIAS ODONTOLÓGICAS                  2414.0  2540.0  2134.0  352.0  2405
DESIGN                                  2272.0  1838.0  1841.0  254.0  1900
ENGENHARIA CIVIL                        2399.0  2089.0  1989.0  254.0  1920
ENGENHARIA DE SOFTWARE                  2477.0  2222.0  1887.0  264.0  1890
FILOSOFIA                               2170.0  2048.0  1773.0  302.0  1903
GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO  2266.0  1891.0  1771.0  252.0  1855

Ajuste do formato da tabela, convertendo para inteiro

In [85]:
for col in emprestimos_pos_graduacao_e_curso_pivot:
    emprestimos_pos_graduacao_e_curso_pivot[col] = emprestimos_pos_graduacao_e_curso_pivot[col].astype('int')

In [86]:
emprestimos_pos_graduacao_e_curso_pivot

ANO                                     2017  2018  2019  2020  2022
CURSO
ADMINISTRAÇÃO                           2538  2316  1692   269  1905
ARQUITETURA E URBANISMO                 2209  1917  1818   257  1896
ARTES CÊNICAS                           2115  2082  1812   229  1920
BIOINFORMÁTICA                          2190  1914  1825   263  2302
BIOQUÍMICA                              2294  1944  2057   272  2090
CIÊNCIA E ENGENHARIA DE MATERIAIS       2316  2110  2008   328  2010
CIÊNCIA, TECNOLOGIA E INOVAÇÃO          2415  2365  2026   303  1960
CIÊNCIAS DA SAÚDE                       2434  1986  1825   234  1730
CIÊNCIAS ODONTOLÓGICAS                  2414  2540  2134   352  2405
DESIGN                                  2272  1838  1841   254  1900
ENGENHARIA CIVIL                        2399  2089  1989   254  1920
ENGENHARIA DE SOFTWARE                  2477  2222  1887   264  1890
FILOSOFIA                               2170  2048  1773   302  1903
GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO  2266  1891  1771   252  1855

Criando a função de diferença percentual

In [87]:
def calcula_diferenca_percentual(x,y):
    return round(((x-y)/y)*100,1)

Calculando os percentuais

In [88]:
percentual_2018 = calcula_diferenca_percentual(emprestimos_pos_graduacao_e_curso_pivot.iloc[:,1],emprestimos_pos_graduacao_e_curso_pivot.iloc[:,0])
percentual_2019 = calcula_diferenca_percentual(emprestimos_pos_graduacao_e_curso_pivot.iloc[:,2],emprestimos_pos_graduacao_e_curso_pivot.iloc[:,1])
percentual_2022 = calcula_diferenca_percentual(emprestimos_pos_graduacao_e_curso_pivot.iloc[:,4],emprestimos_pos_graduacao_e_curso_pivot.iloc[:,2])

In [89]:
percentual = pd.DataFrame({
    '2018': percentual_2018,
    '2019': percentual_2018,
    '2022': percentual_2022
})

In [90]:
percentual

                                        2018  2019  2022
CURSO
ADMINISTRAÇÃO                           -8.7  -8.7  12.6
ARQUITETURA E URBANISMO                -13.2 -13.2   4.3
ARTES CÊNICAS                           -1.6  -1.6   6.0
BIOINFORMÁTICA                         -12.6 -12.6  26.1
BIOQUÍMICA                             -15.3 -15.3   1.6
CIÊNCIA E ENGENHARIA DE MATERIAIS       -8.9  -8.9   0.1
CIÊNCIA, TECNOLOGIA E INOVAÇÃO          -2.1  -2.1  -3.3
CIÊNCIAS DA SAÚDE                      -18.4 -18.4  -5.2
CIÊNCIAS ODONTOLÓGICAS                   5.2   5.2  12.7
DESIGN                                 -19.1 -19.1   3.2
ENGENHARIA CIVIL                       -12.9 -12.9  -3.5
ENGENHARIA DE SOFTWARE                 -10.3 -10.3   0.2
FILOSOFIA                               -5.6  -5.6   7.3
GESTÃO DA INFORMAÇÃO E DO CONHECIMENTO -16.5 -16.5   4.7

Plotando o gráfico de barras

In [91]:
fig = px.bar(
    percentual,
    x = percentual.columns,
    y= percentual.index,
    title = 'Diferença percentual de empréstimos entre os anos 2018, 2019, 2022',
    labels={'value': 'Diferença Percentual (%)', 'variable': 'Ano'},
    barmode = 'group'
)
fig.show()