DIA 01 - Importando dados

In [1]:
#IMPORTANDO BIBLIOTECAS
import pandas as pd
import plotly_express as px
import os

#IMPORTANDO DATASETS
caminho_datasets = 'datasets'
lista_de_diretorios = os.listdir(caminho_datasets)

dfs = []

for arquivo in lista_de_diretorios:
    if arquivo.endswith('.csv'):
        caminho_completo = os.path.join(caminho_datasets, arquivo)
        df = pd.read_csv(caminho_completo)
        dfs.append(df)
    
df_emprestimos_biblioteca = pd.concat(dfs, ignore_index= True)

In [2]:
df_emprestimos_biblioteca

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

In [3]:
df_emprestimos_biblioteca.value_counts()

id_emprestimo  codigo_barras  data_renovacao                 data_emprestimo                data_devolucao                 matricula_ou_siape  tipo_vinculo_usuario
709704         2006021442     2010/01/17 18:56:43.923000000  2010/01/04 09:58:46.522000000  2010/02/01 13:59:02.528000000  2.008010e+09        ALUNO DE GRADUAÇÃO        7
709705         2009032168     2010/01/17 18:56:43.909000000  2010/01/04 09:58:46.549000000  2010/01/20 13:14:34.464000000  2.008010e+09        ALUNO DE GRADUAÇÃO        7
709698         2009047725     2010/01/18 14:44:41.163000000  2010/01/04 09:21:19.099000000  2010/02/02 12:02:38.444000000  2.009047e+09        ALUNO DE GRADUAÇÃO        3
709686         2006017618     2010/01/26 08:07:01.738000000  2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000  2.008112e+09        ALUNO DE PÓS-GRADUAÇÃO    2
2461099        2012008348     2016/06/27 20:35:46.855000000  2016/06/14 11:20:33.254000000  2016/07/11 14:37:29.000000000  2.015022e+09        ALUNO DE GRADUAÇÃO        2
                                                                                                                                                                        ..
1443389        2011018954     2013/03/22 13:18:55.037000000  2013/03/07 11:21:26.480000000  2013/04/08 20:26:07.000000000  2.010046e+09        ALUNO DE GRADUAÇÃO        1
1443390        2009056314     2013/03/21 09:28:45.689000000  2013/03/07 11:21:28.899000000  2013/04/05 18:18:00.000000000  2.011015e+09        ALUNO DE GRADUAÇÃO        1
1443393        2012037906     2013/03/20 20:17:10.574000000  2013/03/07 11:24:19.326000000  2013/03/25 08:58:44.000000000  2.011038e+09        ALUNO DE GRADUAÇÃO        1
1443395        2011033069     2013/04/07 01:06:51.679000000  2013/03/07 11:25:22.661000000  2013/05/07 16:19:34.000000000  2.011106e+09        ALUNO DE PÓS-GRADUAÇÃO    1
10322328       2014070441     2018/01/15 12:26:00.697000000  2017/12/29 18:21:09.060000000  2018/01/31 18:50:25.000000000  2.014063e+09        ALUNO DE GRADUAÇÃO        1
Name: count, Length: 968028, dtype: int64

In [4]:
df_emprestimos_biblioteca = df_emprestimos_biblioteca.drop_duplicates()
df_emprestimos_biblioteca

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

Importando banco de dados .parquet

In [5]:
dados_exemplares = pd.read_parquet('datasets/dados_exemplares.parquet')
dados_exemplares

,id_exemplar,codigo_barras,colecao,biblioteca,status_material,localizacao,registro_sistema
index,,,,,,,
0,5,L000003,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,694,1
1,4,L000002,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,688,1
2,3,L000001,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,638,1
3,7,L000114,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,616,5
5,10,L000041,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,657,15
...,...,...,...,...,...,...,...
568580,1353472,2021011150,Acervo Circulante,Biblioteca Setorial do Núcleo de Educação da I...,REGULAR,951,268231
568581,1353473,2019013454,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,997,268233
568582,1353474,2019012811,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,987,268234
568583,1353475,2019013451,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,764,268235
568584,1353476,2019012276,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,962,268236

Unindo os dois datasets

In [6]:
df_emprestimos_completo = pd.merge(df_emprestimos_biblioteca, dados_exemplares, on= 'codigo_barras')
df_emprestimos_completo

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,25009
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,75019
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,44494
4,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,91736
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,110098
2072518,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,110171
2072519,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,134173
2072520,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,67712
2072521,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,205153

In [7]:
df_emprestimos_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    float64
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
 12  registro_sistema      int64
dtypes: float64(1), int64(4), object(8)
memory usage: 205.6+ MB

DIA 02 - Primeiras manipulações

Criação da coluna 'Classificação CDU' baseada na coluna localização.

In [8]:
df_emprestimos_completo['classe_CDU'] = pd.cut(df_emprestimos_completo['localizacao'], bins= [0, 99, 199, 299,399,499,599,699,799,899,999], labels= ['Generalidades. Ciência e conhecimento', 'Filosofia e psicologia', 'Religião', 'Ciências Sociais', 'Classe vaga', 'Matemática e ciências naturais', 'Ciências aplicadas', 'Belas artes', 'Linguagem. Língua. Linguística', 'Geografia. Biografia. História'] )
df_emprestimos_completo

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema,classe_CDU
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225,Ciências aplicadas
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,25009,Ciências aplicadas
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,75019,Ciências aplicadas
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,44494,Ciências aplicadas
4,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,91736,Ciências aplicadas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,110098,Ciências aplicadas
2072518,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,110171,Ciências aplicadas
2072519,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,134173,Ciências aplicadas
2072520,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,67712,Ciências aplicadas
2072521,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,205153,Generalidades. Ciência e conhecimento

Excluindo a coluna 'registro_sistema'

In [9]:
df_emprestimos_completo.drop(columns='registro_sistema', inplace=True)
df_emprestimos_completo

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,classe_CDU
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,Ciências aplicadas
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,Ciências aplicadas
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,Ciências aplicadas
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,Ciências aplicadas
4,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,Ciências aplicadas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,Ciências aplicadas
2072518,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,Ciências aplicadas
2072519,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,Ciências aplicadas
2072520,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,Ciências aplicadas
2072521,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,Generalidades. Ciência e conhecimento

Verificando o tipo da coluna 'matricula_ou_siape' e convertendo-a para string

In [10]:
df_emprestimos_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    float64
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
 12  classe_CDU            category
dtypes: category(1), float64(1), int64(3), object(8)
memory usage: 191.7+ MB

In [11]:
df_emprestimos_completo['matricula_ou_siape'] = df_emprestimos_completo['matricula_ou_siape'].astype('string')
df_emprestimos_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    string
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
 12  classe_CDU            category
dtypes: category(1), int64(3), object(8), string(1)
memory usage: 191.7+ MB

DIA 03 - Explorando DATETIME dos dados

Verificando a relação entre empréstimo e empréstimo de exemplares

In [12]:
df_emprestimos_completo['id_emprestimo'].value_counts()

id_emprestimo
2772079     3
2010326     3
2014596     3
10240112    3
2595954     3
           ..
1523986     1
1523984     1
1523983     1
1523981     1
2989090     1
Name: count, Length: 2068724, dtype: int64

In [13]:
df_emprestimos_completo.loc[df_emprestimos_completo['id_emprestimo'] == 2772079].reset_index()

,index,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,classe_CDU
0,1864848,2772079,2010082016,2018/12/03 16:05:57.708000000,2018/11/22 18:28:01.619000000,2018/12/11 17:54:14.000000000,20182022833.0,ALUNO DE PÓS-GRADUAÇÃO,1055570,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,670,Ciências aplicadas
1,1864849,2772079,2010082016,2018/12/03 16:05:57.708000000,2018/11/22 18:28:01.619000000,2018/12/11 17:54:14.000000000,20182022833.0,ALUNO DE PÓS-GRADUAÇÃO,1055922,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,693,Ciências aplicadas
2,1864850,2772079,2010082016,2018/12/03 16:05:57.708000000,2018/11/22 18:28:01.619000000,2018/12/11 17:54:14.000000000,20182022833.0,ALUNO DE PÓS-GRADUAÇÃO,1056360,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,389,Ciências Sociais

Essa análise mostra que "id_emprestimo" é cada empréstimo realizado que pode ter 1 ou mais exemplares.
Assim cada linha é o empréstimo de cada exemplar.

Valor total de empréstimos

In [14]:
emprestimos = len(df_emprestimos_completo['id_emprestimo'].unique())
emprestimos

2068724

Exemplares totais emprestados

In [15]:
exemplares = len(df_emprestimos_completo['id_emprestimo'])
exemplares

2072522

In [16]:
df_emprestimos_biblioteca

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

Quantidade de exemplares emprestados por ano

Primeiro converter  coluna de data para uma data válida

In [17]:
df_emprestimos_completo['data_emprestimo'] = pd.to_datetime(df_emprestimos_completo['data_emprestimo'])

In [18]:
emprestimo_ano = df_emprestimos_completo.groupby(df_emprestimos_completo['data_emprestimo'].dt.year)['id_emprestimo'].size()
emprestimo_ano.index.name ='ano'
emprestimo_ano.name = 'quantidade'
emprestimo_ano = emprestimo_ano.reset_index()

Impressão gráfico de linha:

In [19]:
fig = px.line(
    emprestimo_ano,
    x = 'ano',
    y = 'quantidade',
    labels= {
        'ano': 'Ano',
        'quantidade':'Empréstimos'
        },
    title = 'Quantidade de exemplares emprestados do SISBI ao longo dos anos',
    subtitle= '2010 a 2020',
    width = 1000,
    height = 500
)

In [20]:
def ajusta_layout_grafico(fig):
    
    fig.update_layout(
        title_font = dict(size=20, family='Arial', color='black'),
    )

    fig.update_xaxes(
        title_font = dict(size=15, family='Arial'),
        tickfont = dict(size=15, family='Arial'),
        side = 'bottom' # 'bottom' é o padrão, mas é bom para garantir
    )

    fig.update_yaxes(
        title_font = dict(size=15, family='Arial'),
        tickfont = dict(size=15, family='Arial')
    )

In [21]:
fig.show()
ajusta_layout_grafico(fig)

1 - O número de empréstimos começou a diminuir em 2013, tendo queda vertiginosa em 2019.

2 - O ano de 2020 não pode ser valiado igual, pois possui poucos dados.

É importante a direção da biblioteca investigar o que está ocorrendo desde 2013 com os procedimentos realizados. Alguns questionamentos importantes que deve-se levar a direção, para que seja aprofundada em outra análise:

O número de alunos da universidade vem diminuindo?
Como está a pesquisa de satisfação dos usuários da biblioteca?
O acervo está atualizado?
Quais são as estratégias de marketing que a biblioteca está realizando?
O que ocorreu de diferente em 2017 em relação a 2016 e 2015 para que o número tenha se elevado?
E em 2019?

Anlisando a quantidade de empréstimos por mês.

In [22]:
emprestimos_mes = df_emprestimos_completo.groupby(df_emprestimos_completo['data_emprestimo'].dt.month)['id_emprestimo'].size()
emprestimos_mes.index.name = 'mes'
emprestimos_mes.name = 'quantidade'
emprestimos_mes = emprestimos_mes.reset_index()
emprestimos_mes

    mes  quantidade
0     1       67514
1     2      210200
2     3      252185
3     4      208725
4     5      202530
5     6      138123
6     7      123790
7     8      232793
8     9      208234
9    10      188410
10   11      164222
11   12       75796

In [23]:
emprestimos_mes['mes'] = emprestimos_mes['mes'].replace({
    1: 'Janeiro', 2: 'Fevereiro', 3:'Março',
    4: 'Abril', 5: 'Maio', 6: 'Junho',
    7: 'Julho', 8:'Agosto', 9:'Setembro',
    10: 'Outubro', 11: 'Novembro', 12:'Dezembro'

})

In [24]:
emprestimos_mes

          mes  quantidade
0     Janeiro       67514
1   Fevereiro      210200
2       Março      252185
3       Abril      208725
4        Maio      202530
5       Junho      138123
6       Julho      123790
7      Agosto      232793
8    Setembro      208234
9     Outubro      188410
10   Novembro      164222
11   Dezembro       75796

Plotando o gráfico.

In [25]:
fig = px.line(
    emprestimos_mes,
    x = 'mes',
    y = 'quantidade',
    labels = dict(
        mes = 'Mêses',
        quantidade = 'Empréstimos'
    ),
    title = 'Quantidade de exemplares emprestados do SISBI ao longo do ano',
    width= 1200,
    height= 500
)

In [26]:
fig.show()
ajusta_layout_grafico(fig)

1 - Pode-se observar que os meses com maiores números de exemplares emprestados é Março e Agosto

2 - Por ser uma biblioteca universitária faz sentido o comportamento de vale nos meses de Janeiro, Julho e Dezembro, devido ao período de férias.

3 - Não é novidade, mas vale ficar atento que mesmo com a baixa de empréstimos, se todos os colaboradores saíorem de férias a bibliotéca pode não funcionar.
Ainda mais com períodos de inventário que ocorrem uma vez ao ano, ou de dois em dois anos, e o melhor período seria de Dezembro a Janeiro.
Dessa forma mesesd como Maio, Junho e Novembro poderiam ser considerados para isso.

4 - Ocorre uma queda grande no período de Junho. Cabe um alerta para inestigar o que pode estra ocorrendo e criar estratégias e ações de marketing para aumentar o número de exemplares emprestados. Um exemplo é: Uma acão de marketing para que sejam realizados empréstimos para leitura no período de férias.

Vamos analisar ao longo do dia.

In [30]:
emprestimos_hora = df_emprestimos_completo.groupby(df_emprestimos_completo['data_emprestimo'].dt.hour)['id_emprestimo'].size()
emprestimos_hora.index.name = 'hora'
emprestimos_hora.name = 'quantidade'
emprestimos_hora = emprestimos_hora.reset_index()
emprestimos_hora

    hora  quantidade
0      0          17
1      6          14
2      7       18777
3      8      103416
4      9      131273
5     10      185839
6     11      180048
7     12      148754
8     13      126987
9     14      150876
10    15      166672
11    16      210655
12    17      185340
13    18      182520
14    19      102129
15    20      127716
16    21       51191
17    22         247
18    23          51

Organizando valores e plotando gráfico

In [32]:
emprestimos_hora = emprestimos_hora.sort_values(ascending=True, by='quantidade')

In [45]:
fig = px.bar(
    emprestimos_hora,
    x = 'hora',
    y = 'quantidade',
    color='quantidade',
    color_continuous_scale= 'reds',
    labels={
        'hora': 'Horário (24h)',
        'quantidade': 'Quantidade de empréstimos'
    },
    title= 'Quantidade de empréstimos do SISBI ao longo do dia',
    width= 1300,
    height= 500
)

In [47]:
fig.show()
ajusta_layout_grafico(fig)

Através do gráfico é possível identificar que os períodos das 10 h e 16 h são os de maior pico no atendimento de empréstimos.

Períodos do começo da manhã (entre 7h e 9) e da noite (entre 19h e 22) podem ser os melhores horários para que se realizem as demais atividades além do atendimento.

DIA 04

Hoje você vai continuar a questionar ainda mais os seus dados para extrair ainda mais informações deles.

O objetivo será entender a quantidade de empréstimos a partir das variáveis categóricas do seu conjunto de dados.

Variável categórica? Mas o que é isso, Francisco?

Bom, um conjunto de dados é descrito pelas suas características que variam de acordo com cada um, por exemplo: peso, idade, quantidade de páginas, notas, nome da biblioteca, número de empréstimos, número de filhos, etc.

Elas podem ser classificadas em dois grandes grupos que se subdividem em mais dois outros grupos cada.

Quantitativas: são características numéricas que podemos enumerar:


Discreta: possuem apenas valores finitos enumeráveis. Exemplo: número de empréstimos, número de filhos, número de páginas.

Contínua: possuem valores dentro de um intervalo de números. Exemplo: altura, peso, notas.

Categóricas (ou qualitativas): são características não-numéricas para as quais podemos definir categorias.


Nominal: possuem categorias não ordenadas naturalmente. Exemplo: nomes, cores, tema do livro.

Ordinal: são categorias onde está implícito um tipo de ordenamento ou hierarquia. Exemplo: classe social, nível de escolaridade.

Vamos explorar algumas das variáveis categóricas das quais precisaremos extrair mais informações. Elas são:


Tipo de vínculo
Coleção
Biblioteca
Classificação geral da CDU

Ao se analisar uma nova variável, é bem interessante verificar cada uma listando quais são os valores únicos dentro delas.

Para explorar os dados, alguns questionamentos serão pertinentes para a diretoria das bibliotecas, como:


“Como se distribuem os empréstimos de exemplares pelos tipos de vínculo dos usuários?”
Desta forma, a diretoria poderá entender qual é o público que está utilizando a biblioteca e assim tomar decisões em continuar com a estratégia de negócio atual ou modificá-la.

Quais coleções são mais emprestadas?
Da mesma forma, as coleções. Ranquear as coleções mais emprestadas pelo público, será bastante importante para a estratégia atual.

Quais são as bibliotecas com mais ou menos quantidade de empréstimos?
Assim, a diretoria conseguirá entender onde ela deverá melhorar e focar suas iniciativas.

Você visualizará os dados dos empréstimos que aconteceram, mas e os dados que não estão aqui na análise?

Por quais outras perspectivas você pode entender essa tabela de como ela se formou? Comparar bibliotecas de tamanhos diferentes, com públicos diferentes, acervos diferentes... isso faz sentido para a diretoria do sistema de bibliotecas?

Aponte algumas outras métricas que poderiam entrar aqui para enriquecer essa análise.


De quais temas da CDU são os exemplares emprestados?

Entender quais os temas mais procurados pelos usuários é fundamental para o desenvolvimento de novos planos de marketing do acervo. Para que possam não apenas fortalecer o que está sendo utilizado, mas também promover o que não está.

Gere uma tabela de frequência e com o percentual para cada variável.

Como é um trabalho repetitivo, crie uma função que gere a tabela com os valores.

Após geradas as tabelas, traga algumas das suas percepções para as análises com o que você poderá contribuir para a diretoria da biblioteca.