In [2]:
import pandas as pd

df_completo = pd.read_parquet('F:/Programação/Desafio-7-days-of-coding-dashboard/resultados/df_emprestimos_completo.parquet')

In [3]:
df_completo.head(2)

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,classe_CDU
0,709684,L095049,None,2010-01-04 07:44:10.721,2010/01/05 16:26:12.662000000,2008023265.0,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,Ciências aplicadas
1,709685,L167050,None,2010-01-04 07:44:10.750,2010/01/12 07:34:13.934000000,2008023265.0,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,Ciências aplicadas

In [4]:
df_completo.data_emprestimo = pd.to_datetime(df_completo.data_emprestimo)
df_completo.head(2)

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,classe_CDU
0,709684,L095049,None,2010-01-04 07:44:10.721,2010/01/05 16:26:12.662000000,2008023265.0,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,Ciências aplicadas
1,709685,L167050,None,2010-01-04 07:44:10.750,2010/01/12 07:34:13.934000000,2008023265.0,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,Ciências aplicadas

In [5]:
emprestimo_ano = pd.read_parquet('F:/Programação/Desafio-7-days-of-coding-dashboard/resultados/emprestimo_ano.parquet')
emprestimo_ano

     ano  quantidade
0   2010      161394
1   2011      196390
2   2012      221365
3   2013      234749
4   2014      219189
5   2015      213582
6   2016      215900
7   2017      218462
8   2018      194080
9   2019      171801
10  2020       25610

In [6]:
emprestimos_mes = pd.read_parquet('F:/Programação/Desafio-7-days-of-coding-dashboard/resultados/emprestimo_mes.parquet')
emprestimos_mes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   mes         12 non-null     object
 1   quantidade  12 non-null     int64
dtypes: int64(1), object(1)
memory usage: 324.0+ bytes

In [7]:
emprestimos_maximo = emprestimos_mes.nlargest(1, 'quantidade')
mes_emprestimos_maximo = emprestimos_maximo.iloc[0]['mes']
mes_emprestimos_maximo

'Março'

In [8]:
df = df_completo.tipo_vinculo_usuario.value_counts().idxmax()
df

'ALUNO DE GRADUAÇÃO'

In [9]:
emprestimos_hora = df_completo.groupby(df_completo.data_emprestimo.dt.hour)['id_emprestimo'].size().reset_index(name='quantidade')
emprestimos_hora.rename(columns={'data_emprestimo': 'hora'}, inplace=True)
emprestimos_hora

    hora  quantidade
0      0          17
1      6          14
2      7       18777
3      8      103416
4      9      131273
5     10      185839
6     11      180048
7     12      148754
8     13      126987
9     14      150876
10    15      166672
11    16      210655
12    17      185340
13    18      182520
14    19      102129
15    20      127716
16    21       51191
17    22         247
18    23          51

In [10]:
emprestimos_hora = pd.read_parquet('F:/Programação/Desafio-7-days-of-coding-dashboard/resultados/emprestimo_hora.parquet')
emprestimos_hora

    hora  quantidade
0      6          14
1      0          17
2     23          51
3     22         247
4      7       18777
5     21       51191
6     19      102129
7      8      103416
8     13      126987
9     20      127716
10     9      131273
11    12      148754
12    14      150876
13    15      166672
14    11      180048
15    18      182520
16    17      185340
17    10      185839
18    16      210655